### ISSUE TITLE
CLI crash / Error: not opened

### ISSUE THREAD

**Issue by tankmann** [Storj/core#101]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
└─┬ storjshare-cli@3.0.2
  └── storj@0.6.13 
```

Replace the values below using the output from `node --version`.

```
v6.0.0
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
cli should never crash
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
cli crashed with the attached error
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.12\",\"address\":\"104.196.56.59\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1463341589909}","timestamp":"2016-05-15T19:46:29.909Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.13\",\"address\":\"server118.web4you-gmbh.ch\",\"port\":4000,\"nodeID\":\"70b731e6be92504973d509476b2046b0422560c4\",\"lastSeen\":1463341589911}","timestamp":"2016-05-15T19:46:29.911Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.13\",\"address\":\"n.storj.eu\",\"port\":8122,\"nodeID\":\"68c2623db010a07430fc655d7a28459caf41f28f\",\"lastSeen\":1463341589954}","timestamp":"2016-05-15T19:46:29.954Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.13\",\"address\":\"veeit30163.dyndns.org\",\"port\":6000,\"nodeID\":\"6ad8a5a30528b3572f3e80cbd5a3eb4c52b8b8ac\",\"lastSeen\":1463341590003}","timestamp":"2016-05-15T19:46:30.003Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.13\",\"address\":\"server118.web4you-gmbh.ch\",\"port\":4000,\"nodeID\":\"70b731e6be92504973d509476b2046b0422560c4\",\"lastSeen\":1463341590027}","timestamp":"2016-05-15T19:46:30.027Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.13\",\"address\":\"n.storj.eu\",\"port\":8122,\"nodeID\":\"68c2623db010a07430fc655d7a28459caf41f28f\",\"lastSeen\":1463341590077}","timestamp":"2016-05-15T19:46:30.077Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.13\",\"address\":\"veeit30163.dyndns.org\",\"port\":6000,\"nodeID\":\"6ad8a5a30528b3572f3e80cbd5a3eb4c52b8b8ac\",\"lastSeen\":1463341590129}","timestamp":"2016-05-15T19:46:30.129Z"}
{"level":"info","message":"replying to message to e01b090b2644147b1a40bd5dc7e17fbf5ad9e5f9","timestamp":"2016-05-15T19:46:30.179Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.13\",\"address\":\"veeit30163.dyndns.org\",\"port\":6000,\"nodeID\":\"6ad8a5a30528b3572f3e80cbd5a3eb4c52b8b8ac\",\"lastSeen\":1463341590202}","timestamp":"2016-05-15T19:46:30.202Z"}
/usr/local/lib/node_modules/storjshare-cli/node_modules/ws/lib/WebSocket.js:197
  if (this.readyState !== WebSocket.OPEN) throw new Error('not opened');
                                          ^

Error: not opened
    at WebSocket.resume (/usr/local/lib/node_modules/storjshare-cli/node_modules/ws/lib/WebSocket.js:197:49)
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/datachannel/server.js:180:12
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/manager.js:44:5
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/storage/adapters/level/index.js:51:7
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/storage/adapters/level/filestore.js:25:5
    at dispatchError (/usr/local/lib/node_modules/storjshare-cli/node_modules/levelup/lib/util.js:64:35)
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/levelup/lib/levelup.js:222:14`
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Just kept in running (on OSX MacMini Server)... nothing special. 5 tunnels opened.

**Comment by gordonwritescode** [comment]
Not sure that this should make a difference, but it's worth noting that you are running Node 6, while we explicitly depend on LTS (4.x.x).

Regardless, following the stack trace does indicate there can be a condition where the connection closes in between a pause/resume loop while preparing to accept the incoming stream. I'll add some guards there to make sure we don't throw if this happens.
