### ISSUE TITLE
Error: failed to find tunnels

### ISSUE THREAD

**Issue by lunokhod** [Storj/core#108]
I know that this has been discussed before on the slack, but it doesn't appear that there is an issue open regarding not being able to open tunnels. First, I should say that the new version (Farmer: v3.0.3, Core:   v0.6.14) works fine when behind my personal router with port forwarding to 4000. However, on another network, where I have no control, shorjshare crashes with the error "Error: failed to find tunnels". Here is the full output.

~~~~
{"level":"warn","message":"you are not bound to a public address, trying traversal strategies...","timestamp":"2016-05-18T21:18:46.312Z"}
{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-05-18T21:18:46.319Z"}
{"level":"warn","message":"could not connect to NAT device via UPnP","timestamp":"2016-05-18T21:18:48.122Z"}
{"level":"info","message":"node created with nodeID 224105e3e3878eac4a3d4270b907e7cb63eef82f","timestamp":"2016-05-18T21:18:48.131Z"}
{"level":"info","message":"requesting probe from nearest neighbor","timestamp":"2016-05-18T21:18:48.134Z"}
{"level":"info","message":"sending PROBE message to {\"protocol\":\"0.6.14\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"78cfca0e01235db817728aec056d007672ffac63\",\"lastSeen\":1463606328138}","timestamp":"2016-05-18T21:18:48.138Z"}
{"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.6.14\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"78cfca0e01235db817728aec056d007672ffac63\",\"lastSeen\":1463606328206}","timestamp":"2016-05-18T21:18:48.206Z"}
{"type":"info","message":"telemetry report {\"storage\":{\"free\":1073741416,\"used\":408},\"bandwidth\":{\"upload\":34.36,\"download\":25.96},\"contact\":{\"protocol\":\"0.6.14\",\"address\":\"127.0.0.1\",\"nodeID\":\"224105e3e3878eac4a3d4270b907e7cb63eef82f\",\"lastSeen\":1463606326309},\"payment\":\"19cBuNFYFdM9C8RB6bfnhM78RKaHHDVHFm\"}","timestamp":"2016-05-18T21:18:58.981Z"}
{"type":"error","message":"Could not process report","timestamp":"2016-05-18T21:18:59.542Z"}
{"level":"warn","message":"rpc call 73d5d1e625d8c4abe5b3966745bfe353d71c61f4 timed out","timestamp":"2016-05-18T21:19:06.339Z"}
{"level":"info","message":"requesting tunnelers from nearest neighbor","timestamp":"2016-05-18T21:19:06.339Z"}
{"level":"info","message":"sending FIND_TUNNEL message to {\"protocol\":\"0.6.14\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"78cfca0e01235db817728aec056d007672ffac63\",\"lastSeen\":1463606346340}","timestamp":"2016-05-18T21:19:06.340Z"}
{"level":"warn","message":"rpc call a34057ef20ca33b74f09a08e7f8ad8b391a12534 timed out","timestamp":"2016-05-18T21:19:06.384Z"}
{"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `a34057ef20ca33b74f09a08e7f8ad8b391a12534` timed out","timestamp":"2016-05-18T21:19:06.384Z"}
{"level":"warn","message":"rpc call 0b9a8e22876384905ae14045c199079931244228 timed out","timestamp":"2016-05-18T21:19:16.446Z"}
Error: failed to find tunnels, reason: RPC with ID `0b9a8e22876384905ae14045c199079931244228` timed out
    at Object.callback (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:456:9)
    at Transport.RPC._expireCalls (/usr/local/lib/node_modules/storjshare-cli/node_modules/kad/lib/rpc.js:309:19)
    at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
~~~~

**Comment by littleskunk** [comment]
api.storj.io offline because of https://github.com/Storj/core/issues/99 and https://github.com/kadtools/kad/issues/57

As workaround you can try to connect to another node.
