### ISSUE TITLE
TypeError: Cannot read property 'nodeID' of undefined

### ISSUE THREAD

**Issue by subwolf** [Storj/core#112]
Just upgraded cli client, within a minute getting this:

````
farmer-0 {"level":"info","message":"received valid message from {\"protocol\":\"0.6.15\",\"address\":\"server016.storj.dk\",\"port\":5016,\"nodeID\":\"02d7885d60ee045907e51d3a1e5a5f2a7845d2e5\",\"lastSeen\":1463729821964}","timestamp":"2016-05-20T07:37:01.964Z"}
farmer-0 {"level":"info","message":"replying to message to 7409d663a300d4c14a4645659f6adc725da815ae","timestamp":"2016-05-20T07:37:01.966Z"}
farmer-0 {"level":"info","message":"received valid message from {\"protocol\":\"0.6.13\",\"address\":\"104.196.56.59\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1463729822047}","timestamp":"2016-05-20T07:37:02.047Z"}
farmer-0 {"level":"info","message":"replying to message to 87f6ae53b9049f4f91b3bdcbff08e704a2eb700c","timestamp":"2016-05-20T07:37:02.048Z"}
farmer-0 {"level":"info","message":"received valid message from {\"protocol\":\"0.6.13\",\"address\":\"104.196.56.59\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1463729822130}","timestamp":"2016-05-20T07:37:02.131Z"}
farmer-0 {"level":"info","message":"replying to message to 18afb281329d4742c7850285e5778fae6dfb29d6","timestamp":"2016-05-20T07:37:02.131Z"}
farmer-0 {"level":"info","message":"received valid message from {\"protocol\":\"0.6.13\",\"address\":\"104.196.56.59\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1463729822175}","timestamp":"2016-05-20T07:37:02.175Z"}
farmer-0 {"level":"info","message":"replying to message to f2ac80d7c45d30767b1b71de165fbcd5535045b8","timestamp":"2016-05-20T07:37:02.177Z"}
farmer-0 {"level":"info","message":"received valid message from {\"protocol\":\"0.6.13\",\"address\":\"104.196.56.59\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1463729822258}","timestamp":"2016-05-20T07:37:02.258Z"}
farmer-0 {"level":"info","message":"replying to message to 064a6706299c9e76babdd9f55e2c461d2efa5002","timestamp":"2016-05-20T07:37:02.258Z"}
farmer-0 {"level":"info","message":"received valid message from {\"protocol\":\"0.6.13\",\"address\":\"104.196.56.59\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1463729822303}","timestamp":"2016-05-20T07:37:02.303Z"}
farmer-0 {"level":"info","message":"replying to message to 839d95f9c6f276696bc763c97b9db3d914f7b0d3","timestamp":"2016-05-20T07:37:02.303Z"}
farmer-0 {"level":"info","message":"received valid message from {\"protocol\":\"0.6.13\",\"address\":\"104.196.56.59\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1463729822348}","timestamp":"2016-05-20T07:37:02.348Z"}
farmer-0 {"level":"info","message":"replying to message to 4619b338c8c15bcef5389e2a2c71b41102ae7265","timestamp":"2016-05-20T07:37:02.348Z"}
farmer-0 {"level":"info","message":"received valid message from {\"protocol\":\"0.6.13\",\"address\":\"104.196.56.59\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1463729822429}","timestamp":"2016-05-20T07:37:02.429Z"}
farmer-0 {"level":"info","message":"replying to message to fbd28399d35527cbedd3a323af32042afd29865f","timestamp":"2016-05-20T07:37:02.430Z"}
farmer-0 {"level":"info","message":"received valid message from {\"protocol\":\"0.6.13\",\"address\":\"104.196.56.59\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1463729822474}","timestamp":"2016-05-20T07:37:02.474Z"}
farmer-0 {"level":"info","message":"replying to message to ee00969e1ecf69c2fb4ed98b3a269d214cf03448","timestamp":"2016-05-20T07:37:02.476Z"}
farmer-0 {"level":"warn","message":"rpc call 3f4e10fede7962afd2212a9d8cb6dfdc81652da7 timed out","timestamp":"2016-05-20T07:37:02.560Z"}
farmer-0 {"level":"info","message":"replying to message to 1f223d09119b2dfc35736b33c6cf3084bf722e74","timestamp":"2016-05-20T07:37:02.561Z"}
farmer-0 {"level":"warn","message":"rpc call 8c0ba0d3843467582a8f243bd20fc8b61d03ad87 timed out","timestamp":"2016-05-20T07:37:02.639Z"}
farmer-0 {"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `8c0ba0d3843467582a8f243bd20fc8b61d03ad87` timed out","timestamp":"2016-05-20T07:37:02.639Z"}
farmer-0 {"level":"error","message":"Could not locate renter for offer","timestamp":"2016-05-20T07:37:02.640Z"}
farmer-0 {"level":"warn","message":"rpc call 87c8224abed7569546d8e962cbfa4ecdef1af84c timed out","timestamp":"2016-05-20T07:37:02.641Z"}
farmer-0 {"level":"info","message":"replying to message to 5b714a46fc1fe2d9cad7407bd55a5b3b5adfe188","timestamp":"2016-05-20T07:37:02.641Z"}
farmer-0 {"level":"warn","message":"rpc call 32acbfc28686c7b68f6b2eac34e19e7eff1d1d77 timed out","timestamp":"2016-05-20T07:37:02.686Z"}
farmer-0 {"level":"info","message":"replying to message to e9a3f047cfcfd4178f1fc1eb640f917513e27423","timestamp":"2016-05-20T07:37:02.686Z"}
farmer-0 {"level":"warn","message":"rpc call 0ff0b3d8f6c9b9e7389ee9bda39ecffcbc77c746 timed out","timestamp":"2016-05-20T07:37:02.767Z"}
farmer-0 {"level":"info","message":"replying to message to 3a7b06d00b4e4ed4f56b85a9c2538af71303aaa0","timestamp":"2016-05-20T07:37:02.767Z"}
farmer-0 {"level":"warn","message":"rpc call 1bcd3c15fa3a560339c3820718fc9b794b9d2a08 timed out","timestamp":"2016-05-20T07:37:02.847Z"}
farmer-0 {"level":"info","message":"replying to message to ea7403deb2aafeb33f9b66a39f05fd99c75560d9","timestamp":"2016-05-20T07:37:02.848Z"}
farmer-0 {"level":"warn","message":"rpc call 21e554ae8cc7ec37c1bd111d09ae2c12d2af9098 timed out","timestamp":"2016-05-20T07:37:02.892Z"}
farmer-0 {"level":"info","message":"replying to message to 5a7a765110144222bce09fff1bdff344d1bb67a5","timestamp":"2016-05-20T07:37:02.892Z"}
farmer-0 {"level":"warn","message":"rpc call 68955e3a4214d7db8cb9c708bd6e2bbd38f44f85 timed out","timestamp":"2016-05-20T07:37:02.973Z"}
farmer-0 {"level":"info","message":"replying to message to 03cd8a261f6cabaeca31cd17e163e85b08de9348","timestamp":"2016-05-20T07:37:02.973Z"}
farmer-0 {"level":"warn","message":"rpc call 1a6e6f5729dc8de7b908021f21eecea4c4c026cf timed out","timestamp":"2016-05-20T07:37:03.053Z"}
farmer-0 {"level":"info","message":"replying to message to 7b1bbf9358f651ef0cd0915b8220ec06f1959bdd","timestamp":"2016-05-20T07:37:03.054Z"}
farmer-0 {"level":"warn","message":"rpc call 1401f19f30b2981c383b67796f817dc433b4d565 timed out","timestamp":"2016-05-20T07:37:03.098Z"}
farmer-0 {"level":"info","message":"replying to message to fb39162d4351693ad74594ec5d43b11ec5fc7acb","timestamp":"2016-05-20T07:37:03.098Z"}
farmer-0 {"level":"warn","message":"rpc call d66efcd9f76465bc42d27b90bcdc45cdd911cbd7 timed out","timestamp":"2016-05-20T07:37:03.142Z"}
farmer-0 {"level":"info","message":"replying to message to c0e4871cbfa19dccea0fa6aa89b8c7dd36e5a814","timestamp":"2016-05-20T07:37:03.142Z"}
farmer-0 {"level":"warn","message":"rpc call 3056906eadea38c6e03de1d8c6b4f69a78a5b8d4 timed out","timestamp":"2016-05-20T07:37:03.185Z"}
farmer-0 {"level":"info","message":"replying to message to f4b39750986d980eb391af9d5d7d21d91796d879","timestamp":"2016-05-20T07:37:03.186Z"}
farmer-0 {"level":"warn","message":"rpc call c1148c419698544a44084322c0248d001dbe0e82 timed out","timestamp":"2016-05-20T07:37:03.267Z"}
farmer-0 {"level":"info","message":"replying to message to b3b171d05fe870d6d0f6a742d17963c59888a2b5","timestamp":"2016-05-20T07:37:03.267Z"}
farmer-0 {"level":"warn","message":"rpc call 80ff645a8803bbceef36766184daf143d3f0d4fc timed out","timestamp":"2016-05-20T07:37:03.310Z"}
farmer-0 {"level":"info","message":"replying to message to e076028926ed6175115a13d87c42e2b05d04efac","timestamp":"2016-05-20T07:37:03.310Z"}
farmer-0 {"level":"warn","message":"rpc call 9afaab0ea6421c3539d801b84fcd4f64aa2d656d timed out","timestamp":"2016-05-20T07:37:03.392Z"}
farmer-0 {"level":"warn","message":"rpc call bf4067d83e1717eff0273320fca18b586e46ae27 timed out","timestamp":"2016-05-20T07:37:03.395Z"}
farmer-0 {"level":"info","message":"replying to message to 4b232a27acac4336388c38e6af607732c0143795","timestamp":"2016-05-20T07:37:03.395Z"}
farmer-0 {"level":"warn","message":"rpc call 94626aa36f3f1d54fb4903476f41871050a921eb timed out","timestamp":"2016-05-20T07:37:03.439Z"}
farmer-0 {"level":"info","message":"replying to message to b2d44a987cbbb6dcea0fbc4f05eb76a6ca6a87de","timestamp":"2016-05-20T07:37:03.440Z"}
farmer-0 {"level":"warn","message":"rpc call d556c9e0a893c398ebab2a75457af8ca03bc6fc6 timed out","timestamp":"2016-05-20T07:37:03.483Z"}
farmer-0 {"level":"info","message":"replying to message to 46d7a0ba6042b5d08b2e5b9e0dd3afe1038e7771","timestamp":"2016-05-20T07:37:03.483Z"}
farmer-0 {"level":"warn","message":"rpc call a20b14a992e224b38dc265046eabd03410fcaa6e timed out","timestamp":"2016-05-20T07:37:03.529Z"}
farmer-0 {"level":"info","message":"replying to message to c480a2b8ee77e7508d3cd203239c99decb9eb8e5","timestamp":"2016-05-20T07:37:03.529Z"}
farmer-0 {"level":"warn","message":"rpc call 81a4256ae9c30f1ed1b706d05a472b1f5186bc5f timed out","timestamp":"2016-05-20T07:37:03.609Z"}
farmer-0 {"level":"info","message":"replying to message to b306ea9a8fc2b1ed2fe1292250556df70b4f64e9","timestamp":"2016-05-20T07:37:03.609Z"}
farmer-0 {"level":"warn","message":"rpc call 07e0a11d4e46218aae23d664171b3d8a7e33e2d1 timed out","timestamp":"2016-05-20T07:37:03.689Z"}
farmer-0 {"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `07e0a11d4e46218aae23d664171b3d8a7e33e2d1` timed out","timestamp":"2016-05-20T07:37:03.690Z"}
farmer-0 {"level":"error","message":"Could not locate renter for offer","timestamp":"2016-05-20T07:37:03.690Z"}
farmer-0 {"level":"warn","message":"rpc call 4b441e5bd89cd248c3399f40baf7d8aa99efbf5b timed out","timestamp":"2016-05-20T07:37:03.691Z"}
farmer-0 {"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `4b441e5bd89cd248c3399f40baf7d8aa99efbf5b` timed out","timestamp":"2016-05-20T07:37:03.691Z"}
farmer-0 {"level":"error","message":"Could not locate renter for offer","timestamp":"2016-05-20T07:37:03.691Z"}
farmer-0 {"level":"warn","message":"rpc call d361f4b34d86cee15a22cdb09f4ef203b98d94f5 timed out","timestamp":"2016-05-20T07:37:03.691Z"}
farmer-0 {"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `d361f4b34d86cee15a22cdb09f4ef203b98d94f5` timed out","timestamp":"2016-05-20T07:37:03.691Z"}
farmer-0 {"level":"error","message":"Could not locate renter for offer","timestamp":"2016-05-20T07:37:03.692Z"}
farmer-0 {"level":"warn","message":"rpc call e752fd335740aa957ede5f472133f7720fece72c timed out","timestamp":"2016-05-20T07:37:03.692Z"}
farmer-0 {"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `e752fd335740aa957ede5f472133f7720fece72c` timed out","timestamp":"2016-05-20T07:37:03.692Z"}
farmer-0 {"level":"error","message":"Could not locate renter for offer","timestamp":"2016-05-20T07:37:03.692Z"}
farmer-0 TypeError: Cannot read property 'nodeID' of undefined
farmer-0     at Router.getContactByNodeID (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/lib/router.js:154:17)
farmer-0     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/interfaces/farmer.js:143:22
farmer-0     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/storage/adapters/level/index.js:83:7
farmer-0     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/levelup/lib/levelup.js:258:9
````

Causes a restart, happens again within a minute. Hoping it might ease up as other clients upgrade, but of low hope.

**Comment by subwolf** [comment]
Restarted now, working better but no guarantees it won't happen again.

**Comment by gordonwritescode** [comment]
Guh, not checking for null ref in kad. Thanks will fix.

**Comment by gordonwritescode** [comment]
Fixed in kad: https://github.com/kadtools/kad/releases/tag/v1.5.10

Updating the `storj` dependency will pull in the update.

**Comment by subwolf** [comment]
Done, nice one.
