### ISSUE TITLE
Storjshare crashes with "TypeError: Cannot read property 'nodeID' of undefined"

### ISSUE THREAD

**Issue by lunokhod** [Storj/core#116]
After running storjshare for about half a day (Farmer: v3.0.4, Core: v0.6.15, OSX) it crashed with the error "TypeError: Cannot read property 'nodeID' of undefined". Here is output

~~~~
TypeError: Cannot read property 'nodeID' of undefined
    at Router.getContactByNodeID (/usr/local/lib/node_modules/storjshare-cli/node_modules/kad/lib/router.js:154:17)
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/interfaces/farmer.js:143:22
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/storage/adapters/level/index.js:83:7
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/levelup/lib/levelup.js:258:9
~~~~

**Comment by gordonwritescode** [comment]
Resolved. Update dependencies (or re-install): https://github.com/Storj/core/issues/112
