### ISSUE TITLE
Error: failed to find tunnels (Again...)

### ISSUE THREAD

**Issue by lunokhod** [Storj/core#137]
I have been running each iteration of storjshare, and the last few appeared to be working fine with establishing tunnels. However, with the latest iteration
~~~~
Farmer: v3.0.6
Core:   v0.6.16
~~~~
storjfarm is once again crashing because of tunneling problems.
~~~~
{"level":"warn","message":"you are not bound to a public address, trying traversal strategies...","timestamp":"2016-05-26T09:07:54.600Z"}
{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-05-26T09:07:54.608Z"}
{"type":"info","message":"telemetry report {\"storage\":{\"free\":4068193022125,\"used\":646},\"bandwidth\":{\"upload\":7.41,\"download\":25.99},\"contact\":{\"protocol\":\"0.6.16\",\"address\":\"127.0.0.1\",\"port\":4000,\"nodeID\":\"a1844cfb38527bedcdce8a7e28b44fe1d1fe7183\",\"lastSeen\":1464253674597},\"payment\":\"19cBuNFYFdM9C8RB6bfnhM78RKaHHDVHFm\"}","timestamp":"2016-05-26T09:07:54.692Z"}
{"type":"info","message":"sent telemetry report \"Success\"","timestamp":"2016-05-26T09:07:55.259Z"}
{"level":"warn","message":"could not connect to NAT device via UPnP","timestamp":"2016-05-26T09:07:56.412Z"}
{"level":"info","message":"node created with nodeID a1844cfb38527bedcdce8a7e28b44fe1d1fe7183","timestamp":"2016-05-26T09:07:56.421Z"}
{"level":"info","message":"attemting to join network via {\"protocol\":\"0.6.16\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"78cfca0e01235db817728aec056d007672ffac63\",\"lastSeen\":1464253676417}","timestamp":"2016-05-26T09:07:56.422Z"}
{"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.6.16\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"78cfca0e01235db817728aec056d007672ffac63\",\"lastSeen\":1464253676437}","timestamp":"2016-05-26T09:07:56.437Z"}
{"level":"warn","message":"rpc call adbe1cfaea62c4af1765b4ad9b544b9dc6de3330 timed out","timestamp":"2016-05-26T09:08:14.616Z"}
{"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `adbe1cfaea62c4af1765b4ad9b544b9dc6de3330` timed out","timestamp":"2016-05-26T09:08:14.617Z"}
{"level":"info","message":"connected to the storj network via {\"protocol\":\"0.6.16\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"78cfca0e01235db817728aec056d007672ffac63\",\"lastSeen\":1464253676417}","timestamp":"2016-05-26T09:08:14.627Z"}
{"level":"info","message":"requesting probe from nearest neighbor","timestamp":"2016-05-26T09:08:14.628Z"}
{"level":"info","message":"sending PROBE message to {\"protocol\":\"0.6.16\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"78cfca0e01235db817728aec056d007672ffac63\",\"lastSeen\":1464253694628}","timestamp":"2016-05-26T09:08:14.628Z"}
{"level":"warn","message":"rpc call 3135edb78d500fb7f086026838311f97c6691f8b timed out","timestamp":"2016-05-26T09:08:34.632Z"}
{"level":"info","message":"requesting tunnelers from nearest neighbor","timestamp":"2016-05-26T09:08:34.633Z"}
{"level":"info","message":"sending FIND_TUNNEL message to {\"protocol\":\"0.6.16\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"78cfca0e01235db817728aec056d007672ffac63\",\"lastSeen\":1464253714634}","timestamp":"2016-05-26T09:08:34.634Z"}
{"level":"warn","message":"rpc call 013348a1503fce807cf767cb5f5e1cdd13f3dc49 timed out","timestamp":"2016-05-26T09:08:44.710Z"}
Error: failed to find tunnels, reason: RPC with ID `013348a1503fce807cf767cb5f5e1cdd13f3dc49` timed out
    at Object.callback (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:462:9)
    at Transport.RPC._expireCalls (/usr/local/lib/node_modules/storjshare-cli/node_modules/kad/lib/rpc.js:309:19)
    at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
~~~~

**Comment by gordonwritescode** [comment]
@phutchins

**Comment by gordonwritescode** [comment]
Has to be the seed. No tunneling changes made.

**Comment by lunokhod** [comment]
This is the seed written to the default config file
~~~~
storj://api.storj.io:8443/78cfca0e01235db817728aec056d007672ffac63
~~~~

**Comment by gordonwritescode** [comment]
@lunokhod can you try again? @phutchins just fixed a booboo on our bridge instance.

**Comment by lunokhod** [comment]
It seems to be working now (i.e., not crashing). I'm not getting any shards (nor was I for the last couple of days), so if this is a problem, I'll send more debugging info.

**Comment by gordonwritescode** [comment]
Okay, good deal. Note that the process ending on no tunnels is not a crash, but an intentional `process.exit()` as you are unable to join the network. There is an issue lying around here somewhere with a request to keep retrying, so it may change in the future.
