### ISSUE TITLE
Large file upload error

### ISSUE THREAD

**Issue by aleitner** [Storj/core#208]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
/Users/alexleitner/.nvm/versions/node/v4.4.3/lib
└── storj@1.3.1  -> /Users/alexleitner/Desktop/workcode/core
```

Replace the values below using the output from `node --version`.

```
v4.4.3
```

### Expected Behavior

Successfully upload 1.4gb .mkv file using storj upload-file

```
[info]   File successfully stored in bucket.
```

### Actual Behavior

The farmer seems to be closing the connection while the data is continuously trying to store the data

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:870:11)
    at WriteWrap.afterWrite (net.js:769:14)

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Get 1.4gb .mkv
2. storj upload-file bucket-id large.mkv

**Comment by lunokhod** [comment]
I was also unable to upload a large file (1.03 Gb), but the error I got was somewhat different. 
~~~~
 [info]   Shard transfer completed! 85 remaining...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: not opened
    at WebSocket.send (/usr/local/lib/node_modules/storj/node_modules/ws/lib/WebSocket.js:218:38)
    at Writable.stream.Writable.write [as _write] (/usr/local/lib/node_modules/storj/lib/datachannel/client.js:109:20)
    at doWrite (/usr/local/lib/node_modules/storj/node_modules/readable-stream/lib/_stream_writable.js:319:64)
    at writeOrBuffer (/usr/local/lib/node_modules/storj/node_modules/readable-stream/lib/_stream_writable.js:308:5)
    at Writable.write (/usr/local/lib/node_modules/storj/node_modules/readable-stream/lib/_stream_writable.js:246:11)
    at ReadStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at ReadStream.Readable.read (_stream_readable.js:387:10)
    at flow (_stream_readable.js:764:26)
    at Writable.<anonymous> (_stream_readable.js:622:7)
~~~~
It appears that about 40 of the 122 shards were successfully uploaded. I tried to upload the file again, but in doing so, the initial ~40 shards that were successfully uploaded were re-uploaded to the network again. Given that their hashes the second time around should be the same as the first time, this seems to be redundant.
~~~~
storj --version
1.3.1
~~~~

**Comment by bookchin** [comment]
@lunokhod i think that @aleitner and I have effectively eliminated as many of these issues as we can (including the one you had) without requiring a release that propagates the network.

Now the issues is some farmers clocks that are synced close enough to have valid signatures but not enough to accept a consignment immediately after contract negotiation, so that's being handled as well. We will do a new release on Monday.

P.S. We have been able to upload the better part of a 6GB+ MKV to the network several times today. :)
