### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by lunokhod** [Storj/core#216]
I have been running storjshare for some time, and finally ran out of disk space. This has led to several nonstandard problems.

First, I realized this because storjshare was hogging 100% of the CPU. I checked the logs and saw the following that was being repeated over and over again.
~~~~
storjshare-3 OpenError: IO error: /Volumes/Lunokhod-backup/storj/farmer.db/MANIFEST-330458: No space left on device
storjshare-3     at /usr/local/lib/node_modules/storjshare-cli/node_modules/levelup/lib/levelup.js:119:34
storjshare-3     at /usr/local/lib/node_modules/storjshare-cli/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
storjshare-3 {"level":"warn","message":"you are not bound to a public address, trying traversal strategies...","timestamp":"2016-06-26T08:47:10.029Z"}
storjshare-3 {"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-06-26T08:47:10.033Z"}
storjshare-3 {"type":"info","message":"telemetry report {\"storage\":{\"free\":85897909794,\"used\":1436126},\"bandwidth\":{\"upload\":3.52,\"download\":20.55},\"contact\":{\"protocol\":\"0.7.0\",\"address\":\"127.0.0.1\",\"port\":4000,\"nodeID\":\"b67e00024e1153a99b5ef76b74fb52ce4118275f\",\"lastSeen\":1466930830026},\"payment\":\"19cBuNFYFdM9C8RB6bfnhM78RKaHHDVHFm\"}","timestamp":"2016-06-26T08:47:11.251Z"}
storjshare-3 {"level":"info","message":"successfully traversed NAT via UPnP","timestamp":"2016-06-26T08:47:11.419Z"}
storjshare-3 {"level":"info","message":"node created with nodeID b67e00024e1153a99b5ef76b74fb52ce4118275f","timestamp":"2016-06-26T08:47:11.427Z"}
storjshare-3 {"level":"info","message":"attempting to join network via storj://server011.storj.dk:5011/0698546f86ae720e3393f1e900c44a1b64678c9a","timestamp":"2016-06-26T08:47:11.429Z"}
storjshare-3 {"level":"info","message":"successfully traversed NAT via UPnP","timestamp":"2016-06-26T08:47:11.433Z"}
storjshare-3 {"level":"info","message":"tunnel server bound and port mapped: 4001","timestamp":"2016-06-26T08:47:11.433Z"}
storjshare-3 {"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.7.0\",\"address\":\"server011.storj.dk\",\"port\":5011,\"nodeID\":\"0698546f86ae720e3393f1e900c44a1b64678c9a\",\"lastSeen\":1466930831443}","timestamp":"2016-06-26T08:47:11.443Z"}
...
~~~~
I next checked the size of my farmer.db folder, and found that it was 83 274 088 546 bytes, even though I put the following in my config file
~~~~
    "size": 80,
    "unit": "GB"
~~~~
So, it appears that my maximum shared space was not being respected. Looking at the logs, it appears that after getting the IO error, that I am trying to reconnect to the storj network again as well. Finally, all this is taking up too much CPU power.
~~~~
StorjShare: 4.0.4
Core:       1.3.1
Protocol:   0.7.0
~~~~

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-cli/issues/92

**Comment by lunokhod** [comment]
I don't think that this is a duplicate issue. I set the amount of space that I wanted to share to be less than the size of the drive. Storjshare did not respect this. On top of that, the subsequent behaviour described above needs to be fixed.
