### ISSUE TITLE
Panic when invalid passphrase entered while downloading a file

### ISSUE THREAD

**Issue by sokoow** [Storj/core#305]
### Package Versions

```
/usr/local/lib
└── storj@2.0.7 
```

Replace the values below using the output from `node --version`.

```
v4.2.6
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

When put an invalid passphrase for the file, I'd expect to see an error message, not a crash.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
 [...]  > Enter your passphrase to unlock your keyring  >  *******

readline.js:924
            throw err;
            ^

SyntaxError: Unexpected token e
    at Object.parse (native)
    at KeyRing.get (/usr/local/lib/node_modules/storj/lib/keyring.js:81:10)
    at /usr/local/lib/node_modules/storj/bin/storj.js:607:28
    at /usr/local/lib/node_modules/storj/bin/storj.js:141:5
    at /usr/local/lib/node_modules/storj/node_modules/prompt/lib/prompt.js:336:32
    at /usr/local/lib/node_modules/storj/node_modules/utile/node_modules/async/lib/async.js:154:25
    at assembler (/usr/local/lib/node_modules/storj/node_modules/prompt/lib/prompt.js:333:9)
    at /usr/local/lib/node_modules/storj/node_modules/prompt/lib/prompt.js:342:32
    at /usr/local/lib/node_modules/storj/node_modules/prompt/lib/prompt.js:625:5
    at Interface.onLine (/usr/local/lib/node_modules/storj/node_modules/read/lib/read.js:111:5)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. storj download-file bucket-hash file-hash test.file
2. put invalid passphrase
3. get an error message

**Comment by sokoow** [comment]
Additionally this creates a 0 size file

**Comment by bookchin** [comment]
Update to 2.1.0 and try again

**Comment by sokoow** [comment]
same on 2.1.0:

```
readline.js:924
            throw err;
            ^

SyntaxError: Unexpected token i
    at Object.parse (native)
    at KeyRing._decrypt (/usr/local/lib/node_modules/storj/lib/keyring.js:269:15)
    at KeyRing.get (/usr/local/lib/node_modules/storj/lib/keyring.js:168:21)
    at /usr/local/lib/node_modules/storj/bin/storj.js:669:28
    at /usr/local/lib/node_modules/storj/bin/storj.js:143:5
    at /usr/local/lib/node_modules/storj/node_modules/prompt/lib/prompt.js:336:32
    at /usr/local/lib/node_modules/storj/node_modules/utile/node_modules/async/lib/async.js:154:25
    at assembler (/usr/local/lib/node_modules/storj/node_modules/prompt/lib/prompt.js:333:9)
    at /usr/local/lib/node_modules/storj/node_modules/prompt/lib/prompt.js:342:32
    at /usr/local/lib/node_modules/storj/node_modules/prompt/lib/prompt.js:625:5
    at Interface.onLine (/usr/local/lib/node_modules/storj/node_modules/read/lib/read.js:111:5)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface._line (readline.js:549:8)
    at Interface._ttyWrite (readline.js:826:14)
```

**Comment by sokoow** [comment]
additionally I get " [Thu Aug 04 2016 17:51:43 GMT+0100 (IST)] [error]  Could not unlock keyring, bad password?" when putting the correct password now, is 2.1.0 breaking the keyring ?

**Comment by bookchin** [comment]
Try deleting `~/.storjcli/key.ring/.verify` and try again

**Comment by sokoow** [comment]
that works with the right password now

**Comment by bookchin** [comment]
Awesome! :)
