### ISSUE TITLE
Speed tests: Too many open files

### ISSUE THREAD

**Issue by subwolf** [Storj/core#339]
Storj Core V3.0.1. Think speedtest files are not being closed, causing an error eventually. Keymetrics emailed me with this error:

````
Error: EMFILE: too many open files, open '/tmp/speedtest-d23f0dbfb8c2e6abc22b8598e15359b13a8e86bf.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.module.exports.report (/usr/local/lib/node_modules/storjshare-cli/lib/reporter.js:16:22)
    at null._onTimeout (/usr/local/lib/node_modules/storjshare-cli/lib/reporter.js:71:22)
    at Timer.listOnTimeout (timers.js:92:15)
````

**Comment by bookchin** [comment]
Thanks, can you open this at https://github.com/bookchin/myspeed
