### ISSUE TITLE
File upload error (core v.3.0.4) - windows 10

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#353]
### Package Versions

npm --version: 2.15.9

node --version: 4.5.0

core version : 3.0.4

python --version: 2.7.12

OS: windows 10 home edition

### Expected Behavior

file uploaded, clean exit

### Actual Behavior

[Fri Aug 19 2016 20:29:09 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0","address":"173.206.92.114","port":4020,"nodeID":"6ef80edcff7e4bfc6134f189029148b9ab8f13d8","lastSeen":1471631354335}
 [Fri Aug 19 2016 20:29:09 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Fri Aug 19 2016 20:29:22 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
 [Fri Aug 19 2016 20:29:22 GMT+0200 (W. Europe Daylight Time)] [warn]   Error occurred. Triggering cleanup...
 [Fri Aug 19 2016 20:29:22 GMT+0200 (W. Europe Daylight Time)] [info]   Cleaning up...
 [Fri Aug 19 2016 20:29:22 GMT+0200 (W. Europe Daylight Time)] [info]   Finished cleaning!
 [Fri Aug 19 2016 20:29:22 GMT+0200 (W. Europe Daylight Time)] [error]  No storage offers were received
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error
    at WebSocket.WritableDataChannelStream._handleClosed (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\lib\data-channels\writable-stream.js:112:18)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at WebSocket.cleanupWebsocketResources (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\node_modules\ws\lib\WebSocket.js:950:8)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

C:\WINDOWS\system32>

### Steps to Reproduce

upload a file

**Comment by MeijeSibbel** [comment]
After the '[error]  No storage offers were received' message the process sits there for 15-30 minutes before giving the error message.

**Comment by MeijeSibbel** [comment]
The issue only surfaces if i use the -r and -c command, my case -r 15, -c 15, i don't know which one causes it, could be just one of the commands or both combined.

**Comment by littleskunk** [comment]
@MeijeSibbel -r should not be a problem but if you set -c to high I would expect problems. Default is 6.

**Comment by MeijeSibbel** [comment]
Farmers are not accepting shards of a 100GB file for some reason.

[10:19]  
[Fri Aug 19 2016 22:14:30 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 52.232.133.218:4100

**Comment by bookchin** [comment]
Give it the weekend for network to upgrade. Part if the new release targets an issue with shard sizes and contract negotiation.

**Comment by MeijeSibbel** [comment]
After 3 hours of uploading a 100GB file i get this error:

 [Sat Aug 20 2016 04:16:57 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
 [Sat Aug 20 2016 04:16:57 GMT+0200 (W. Europe Daylight Time)] [warn]   Error occurred. Triggering cleanup...
 [Sat Aug 20 2016 04:16:57 GMT+0200 (W. Europe Daylight Time)] [info]   Cleaning up...
fs.js:758
  return binding.rmdir(pathModule._makeLong(path));
                 ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\meije\AppData\Local\Temp\storj-67940kd38Ws5GfEUY'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at _rmdirRecursiveSync (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\node_modules\tmp\lib\tmp.js:285:10)
    at _cleanupCallback (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\node_modules\tmp\lib\tmp.js:409:5)
    at cleanup (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\bin\storj.js:478:11)
    at UploadState.callback (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\bin\storj.js:507:23)
    at _handleError (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:485:18)
    at C:\Users\meije\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:519:16
    at C:\Users\meije\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:342:16
    at Request._callback (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:961:14)
    at Request.self.callback (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\meije\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)

C:\WINDOWS\system32>
