### ISSUE TITLE
upload-file fails on windows file path must be string

### ISSUE THREAD

**Issue by computeronix** [Storj/core#375]
### Package Versions

```
C:\Users\user\AppData\Roaming\npm
└── storj@3.1.0
```
```
v4.5.0
```

### Expected Behavior

```
When performing upload-file and the required parameters it should work
```

### Actual Behavior

```
when using upload-file it fails with the error message below.  Here is an example command

storj upload-file 000000 poo

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.statSync (fs.js:844:18)
    at C:\Users\user\AppData\Roaming\npm\node_modules\storj\bin\actions\fi
les.js:77:12
    at iterate (C:\Users\user\AppData\Roaming\npm\node_modules\storj\node_
modules\async\lib\async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (C:\Users\user\AppD
ata\Roaming\npm\node_modules\storj\node_modules\async\lib\async.js:281:9)
    at Command.module.exports.upload (C:\Users\user\AppData\Roaming\npm\no
de_modules\storj\bin\actions\files.js:74:9)
    at Command.listener (C:\Users\user\AppData\Roaming\npm\node_modules\st
orj\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (C:\Users\user\AppData\Roaming\npm\node_modules\s
torj\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\user\AppData\Roaming\npm\node_modules\storj
\node_modules\commander\index.js:458:21)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\
storj\bin\storj.js:265:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)


```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by MeijeSibbel** [comment]
I get this same error when a path to a file/folder or file name contains spaces.

**Comment by computeronix** [comment]
Can get it to succeed if i throw it in the root C:\

Note: if I put an invalid file such as ban     (its really ban.txt)   it errors out with same message   instead it should respond saying invalid file/path

**Comment by computeronix** [comment]
also if you add the command

storj upload-file 57c3a9f281e21cfd4f3d973f C:\bginfo\bg.jpg -r 9

it fails with same error

but

storj upload-file 57c3a9f281e21cfd4f3d973f C:\bginfo\bg.jpg -h

works and

storj -r 9 upload-file 57c3a9f281e21cfd4f3d973f C:\bginfo\bg.jpg

works
