### ISSUE TITLE
Unable to download file

### ISSUE THREAD

**Issue by NicoNet** [Storj/core#400]
### Package Versions

```
/usr/local/lib
├── storj@3.1.1
└─┬ storjshare-cli@5.0.2
  └── storj@2.2.0
```

```
v4.4.7
```

### Expected Behavior

One should be able to download a file that has been uploaded without the application crashing.

### Actual Behavior

```
storj -k a download-file 57cf5bea8c71dce55bc751a5 57cf6c4c8d8000733b7ec8c0 abc.txt
 [Tue Sep 06 2016 22:11:38 GMT-0400 (EDT)] [info]   Name: PR9I9CxPM8MqNpygHMGF, Type: application/octet-stream, Size: 100001 bytes, ID: 57cf6c4c8d8000733b7ec8c0
fs.js:844
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat 'abc.txt'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at /usr/local/lib/node_modules/storj/bin/actions/files.js:329:12
    at /usr/local/lib/node_modules/storj/bin/actions/files.js:54:16
    at Array.forEach (native)
    at /usr/local/lib/node_modules/storj/bin/actions/files.js:47:11
    at Request._callback (/usr/local/lib/node_modules/storj/lib/bridge-client/index.js:985:5)
    at Request.self.callback (/usr/local/lib/node_modules/storj/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/storj/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/storj/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

### Steps to Reproduce

1. upload a file
2. try to download it
3. ...
4. Profit!

**Comment by aleitner** [comment]
This was resolved with 3.1.2 You were able to download a file in 3.1.1 but only if you specified a folder to download to rather than the folder + name of the file
