### ISSUE TITLE
Piping output to head produces an error when output is cut short (list-buckets, list-files)

### ISSUE THREAD

**Issue by NicoNet** [Storj/core#402]
### Package Versions

```
/usr/local/lib
├── storj@3.1.1
└─┬ storjshare-cli@5.0.2
  └── storj@2.2.0
```

```
v4.4.7
```

### Expected Behavior

An error shouldn't be produced when piping output to head.

### Actual Behavior

Piping the output of list-files and list-buckets to head results in an error after the output.

```
storj list-files 57cf5bea8c71dce55bc751a5|head
 [Tue Sep 06 2016 22:26:32 GMT-0400 (EDT)] [info]   Name: FbiXbjZrpdRJ8VKTtoLv, Type: application/octet-stream, Size: 100001 bytes, ID: 57cf5bfc5f1f579c7b386d58
 [Tue Sep 06 2016 22:26:32 GMT-0400 (EDT)] [info]   Name: PfP4ynwdn0iADGcY2PBC, Type: application/octet-stream, Size: 100001 bytes, ID: 57cf5c1a0b2a6660048db783
 [Tue Sep 06 2016 22:26:32 GMT-0400 (EDT)] [info]   Name: 9nEJFH48xhwIkUu1numl, Type: application/octet-stream, Size: 100001 bytes, ID: 57cf5c395f1f579c7b386d8d
 [Tue Sep 06 2016 22:26:32 GMT-0400 (EDT)] [info]   Name: KjwmKUBBxW7Hd6Cj64Xm, Type: application/octet-stream, Size: 100001 bytes, ID: 57cf5c405eb4d0fc622ff8cb
 [Tue Sep 06 2016 22:26:32 GMT-0400 (EDT)] [info]   Name: U1nHcUa1xSufGcSQ2X5F, Type: application/octet-stream, Size: 100001 bytes, ID: 57cf5c5b0b2a6660048db7a4
 [Tue Sep 06 2016 22:26:32 GMT-0400 (EDT)] [info]   Name: K5mlrYBEtfAt9P2RTgIz, Type: application/octet-stream, Size: 100001 bytes, ID: 57cf5c695f1f579c7b386da5
 [Tue Sep 06 2016 22:26:32 GMT-0400 (EDT)] [info]   Name: Y4gWf6AGEtsEwLFK6vab, Type: application/octet-stream, Size: 100001 bytes, ID: 57cf5c758d8000733b7eb00b
 [Tue Sep 06 2016 22:26:32 GMT-0400 (EDT)] [info]   Name: DIwUrYgQb3NYoZCAkqaP, Type: application/octet-stream, Size: 100001 bytes, ID: 57cf5c8b0b2a6660048db7f9
 [Tue Sep 06 2016 22:26:32 GMT-0400 (EDT)] [info]   Name: jCgfNOBW0ShqKGyFEZrM, Type: application/octet-stream, Size: 100001 bytes, ID: 57cf5c8d0b2a6660048db7fb
 [Tue Sep 06 2016 22:26:32 GMT-0400 (EDT)] [info]   Name: IScWXZLTPcNrj10Yi9Lp, Type: application/octet-stream, Size: 100001 bytes, ID: 57cf5ca38d8000733b7eb054
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:873:11)
    at WriteWrap.afterWrite (net.js:785:14)

------------------------------------------------------------------------------------------

storj list-buckets|head
 [Tue Sep 06 2016 22:26:51 GMT-0400 (EDT)] [info]   ID: 57a658e8905cfece30b13d0e, Name: uhn, Storage: 10, Transfer: 30
 [Tue Sep 06 2016 22:26:51 GMT-0400 (EDT)] [info]   ID: 57a66c34dd072de41855c118, Name: New Bucket, Storage: 10, Transfer: 30
 [Tue Sep 06 2016 22:26:51 GMT-0400 (EDT)] [info]   ID: 57a66c4c3a91dae863cfb03d, Name: New Bucket, Storage: 10, Transfer: 30
 [Tue Sep 06 2016 22:26:51 GMT-0400 (EDT)] [info]   ID: 57a66c6733c81c746744d22e, Name: New Bucket, Storage: 10, Transfer: 30
 [Tue Sep 06 2016 22:26:51 GMT-0400 (EDT)] [info]   ID: 57a66c718f266a7d4e364fc5, Name: New Bucket, Storage: 10, Transfer: 30
 [Tue Sep 06 2016 22:26:51 GMT-0400 (EDT)] [info]   ID: 57a66c7b3a91dae863cfb051, Name: New Bucket, Storage: 10, Transfer: 30
 [Tue Sep 06 2016 22:26:51 GMT-0400 (EDT)] [info]   ID: 57a66c8cdd072de41855c132, Name: New Bucket, Storage: 10, Transfer: 30
 [Tue Sep 06 2016 22:26:51 GMT-0400 (EDT)] [info]   ID: 57a66c9c3a91dae863cfb053, Name: New Bucket, Storage: 10, Transfer: 30
 [Tue Sep 06 2016 22:26:51 GMT-0400 (EDT)] [info]   ID: 57a66caa9a1e48163c33aff9, Name: New Bucket, Storage: 10, Transfer: 30
 [Tue Sep 06 2016 22:26:51 GMT-0400 (EDT)] [info]   ID: 57a66cb133c81c746744d241, Name: New Bucket, Storage: 10, Transfer: 30
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:873:11)
    at WriteWrap.afterWrite (net.js:785:14)

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Create several buckets
2. list the buckets and pipe the output to head

1. upload several files to a bucket
2. list the contents of the bucket and pipe the output to head

**Comment by vevarm** [comment]
I have seen this too, not very major though.
