### ISSUE TITLE
core 1.3.1 upload error ('return binding.rmdir(pathModule._makeLong(path));' )

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#407]
### Package Versions

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
   └── storj --version: 3.1.1

```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

clean exit

### Command
```

storj -k meije0612 -c 20 upload-file 57af3a1e8f266a7d4e391055 D:\20GB

```

### Actual Behavior

```

 [Thu Sep 08 2016 07:47:40 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Thu Sep 08 2016 07:47:57 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for d8b78d7852c01b7e8fdf8084169ac8c8c31f1430 (retry: 7)
 [Thu Sep 08 2016 07:48:45 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for d8b78d7852c01b7e8fdf8084169ac8c8c31f1430 (retry: 8)
 [Thu Sep 08 2016 07:48:46 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\4859ae922333 index 19
 [Thu Sep 08 2016 07:48:46 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 17a3eea26d83c17e54721e8679b90d897ffd4248
 [Thu Sep 08 2016 07:48:47 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Thu Sep 08 2016 07:48:47 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Thu Sep 08 2016 07:48:47 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for ea7589c6052b303335ba22f1ce98eddfd6d48f3a (retry: 0)
 [Thu Sep 08 2016 07:48:48 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.1","address":"neomark.go.ro","port":4070,"nod
eID":"26469e2a9d0fdcaabb782e89268fdecbebf08e6b","lastSeen":1473313723888}
 [Thu Sep 08 2016 07:48:49 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Thu Sep 08 2016 07:49:09 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for ea7589c6052b303335ba22f1ce98eddfd6d48f3a (retry: 1)
 [Thu Sep 08 2016 07:49:21 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
 [Thu Sep 08 2016 07:49:21 GMT+0200 (W. Europe Daylight Time)] [warn]   [ 20GB ] Error occurred. Triggering cleanup...
 [Thu Sep 08 2016 07:49:21 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Cleaning up...
fs.js:758
  return binding.rmdir(pathModule._makeLong(path));
                 ^

Error: ENOTEMPTY: directory not empty, rmdir 'D:\temp\storj-4108p7ID3YI6mCJw'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at _rmdirRecursiveSync (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\tmp\lib\tmp.js:285:10)
    at _cleanupCallback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\tmp\lib\tmp.js:409:5)
    at cleanup (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\bin\actions\files.js:163:15)
    at UploadState.callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\bin\actions\files.js:204:27)
    at _handleError (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:494:18)
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:528:16
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:346:16
    at Request._callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:982:14)
    at Request.self.callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)

C:\Windows\system32>

```

### Steps to Reproduce

upload a large file

**Comment by super3** [comment]
@MeijeSibbel Please use the issue template in the future.
