### ISSUE TITLE
Error: ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#414]
### Package Versions

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

No free space warning.

### Actual Behavior

```
C:\Windows\system32>storj -k meije0612 -c 20 upload-file 57af3a1e8f266a7d4e391055 D:\storj\farmer.db\*
 [Fri Sep 09 2016 23:02:07 GMT+0200 (W. Europe Daylight Time)] [info]   773 file(s) to upload.
 [Fri Sep 09 2016 23:02:08 GMT+0200 (W. Europe Daylight Time)] [info]   Generating encryption key...
 [Fri Sep 09 2016 23:02:11 GMT+0200 (W. Europe Daylight Time)] [info]   Encrypting file "D:/storj/farmer.db/001131.ldb"
 [Fri Sep 09 2016 23:02:13 GMT+0200 (W. Europe Daylight Time)] [info]   [ 001131.ldb ] Encryption complete!
 [Fri Sep 09 2016 23:02:13 GMT+0200 (W. Europe Daylight Time)] [info]   [ 001131.ldb ] Creating storage token...
 [Fri Sep 09 2016 23:02:13 GMT+0200 (W. Europe Daylight Time)] [info]   [ 001131.ldb ] Storing file, hang tight!
 [Fri Sep 09 2016 23:02:14 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\f0b39a59853c index 0
 [Fri Sep 09 2016 23:02:14 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: cd3c42e94c26826271498f4068c78bc947330383
 [Fri Sep 09 2016 23:02:14 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Fri Sep 09 2016 23:02:14 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Fri Sep 09 2016 23:02:14 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for cd3c42e94c26826271498f4068c78bc947330383 (retry: 0)
 [Fri Sep 09 2016 23:04:13 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for cd3c42e94c26826271498f4068c78bc947330383 (retry: 1)
 [Fri Sep 09 2016 23:06:01 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for cd3c42e94c26826271498f4068c78bc947330383 (retry: 2)
 [Fri Sep 09 2016 23:07:34 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for cd3c42e94c26826271498f4068c78bc947330383 (retry: 3)
 [Fri Sep 09 2016 23:07:36 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.1","address":"server2dk.ddns.net","port":4006
,"nodeID":"ca96a70d929f269233b37c1dbdd9891a510d548c","lastSeen":1473455249968}
 [Fri Sep 09 2016 23:07:36 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Fri Sep 09 2016 23:07:40 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 0 remaining...
 [Fri Sep 09 2016 23:07:43 GMT+0200 (W. Europe Daylight Time)] [info]   Transfer finished, creating entry...
fs.js:658
    return binding.writeBuffer(fd, buffer, offset, length, position);
                   ^

Error: ENOSPC: no space left on device, write
    at Error (native)
    at Object.fs.writeSync (fs.js:658:20)
    at Object.fs.writeFileSync (fs.js:1165:24)
    at KeyRing._saveKeyToDisk (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\crypto-tools\keyring.js:199:13)
    at KeyRing.set (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\crypto-tools\keyring.js:189:8)
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\bin\actions\files.js:213:33
    at Request._callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:985:5)
    at Request.self.callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

C:\Windows\system32>
```

### Steps to Reproduce

upload a file with no free disk space.

**Comment by bookchin** [comment]
Uploading a file includes staging an encrypted version of the file before uploading in, so you must have enough space for a copy of the encrypted file.

**Comment by MeijeSibbel** [comment]
Of course, i understand it from a technical point of view but isn't it better for core to prevent a user uploading a file/set of files if there is no space, imagine if somebody is uploading a folder with 1k files and at file 900 the space runs out and the app crashes. Making a function that takes the size of the total data to be created by core, minus the free space available it can warn a user before he or she starts a upload process that will never finish successfully because somewhere along the upload process the free space runs out. Or to create something like a timeout with warning for the user to quickly free up some space and press "ok" to continue the upload. A per-check for free space should in my opinion always be done.

**Comment by MeijeSibbel** [comment]
sending some sort of used space/free space telemetry/info will also allow apps or machines with dynamic or virtual space allocation to work better.

**Comment by bookchin** [comment]
On your second point, we do already collect space metrics for telemetry.
