### ISSUE TITLE
Excessive memory usage when uploading large files

### ISSUE THREAD

**Issue by 1credit** [Storj/core#426]
### Package Versions

Replace the values below using the output from `npm list storj`. Use `npm list -g storj` if installed globally.

```
Storj 3.1.2
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```
### Expected Behavior

Memory usage should not be significantly affected by the uploaded file size.

```

```
### Actual Behavior

Uploading a 22GB file drives the memory usage of the node process to 17.5GB - totally unreasonable, since this exceeds the capacity of most home systems and forces excessive paging.

```

```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. ...
2. ...
3. ...

**Comment by MeijeSibbel** [comment]
```
[Sun Sep 25 2016 23:02:31 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Remote host terminated early
 [Sun Sep 25 2016 23:02:31 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Sun Sep 25 2016 23:02:34 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Sun Sep 25 2016 23:02:35 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Channel is already active
 [Sun Sep 25 2016 23:02:36 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Channel is already active
 [Sun Sep 25 2016 23:02:36 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Remote host terminated early
 [Sun Sep 25 2016 23:02:37 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Remote host terminated early
 [Sun Sep 25 2016 23:02:37 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Channel is already active
 [Sun Sep 25 2016 23:02:37 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Channel is already active
 [Sun Sep 25 2016 23:02:37 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Channel is already active
 [Sun Sep 25 2016 23:02:41 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: connect ETIMEDOUT 212.24.108.168:2601
 [Sun Sep 25 2016 23:02:41 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Channel is already active
 [Sun Sep 25 2016 23:03:07 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 3ada2917383e940561eb6d635c50ab344f14f04b (retry: 3)
 [Sun Sep 25 2016 23:03:50 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 3ada2917383e940561eb6d635c50ab344f14f04b (retry: 4)
C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\storj-lib\lib\audit-tools\audit-stream.js:0



Error: toString failed
    at Buffer.toString (buffer.js:440:11)
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\storj-lib\lib\audit-tools\audit-stream.js:76:26
    at Array.forEach (native)
    at AuditStream._write (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\storj-lib\lib\audit-tools\audit-stream.js:
74:16)
    at doWrite (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\storj-lib\node_modules\readable-stream\lib\_stream_wr
itable.js:319:64)
    at writeOrBuffer (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\storj-lib\node_modules\readable-stream\lib\_str
eam_writable.js:308:5)
    at AuditStream.Writable.write (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\storj-lib\node_modules\readable-st
ream\lib\_stream_writable.js:246:11)
    at ReadStream.ondata (_stream_readable.js:542:20)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at ReadStream.Readable.push (_stream_readable.js:111:10)
    at onread (fs.js:1739:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)

Waiting for 0 seconds, press a key to continue ...

C:\Users\Dani Marion\Desktop>(
echo 2
 storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*
 TIMEOUT 2
)
2
 [Sun Sep 25 2016 23:07:03 GMT+0200 (W. Europe Daylight Time)] [warn]   A redundancy of 0 means files will not be mirrored!
 [Sun Sep 25 2016 23:07:03 GMT+0200 (W. Europe Daylight Time)] [info]   30 file(s) to upload.
 [Sun Sep 25 2016 23:07:06 GMT+0200 (W. Europe Daylight Time)] [info]   Generating encryption key...
 [Sun Sep 25 2016 23:07:06 GMT+0200 (W. Europe Daylight Time)] [info]   Encrypting file "D:/films/A.Promise.2013.720p.BluRay.x264.YIFY.mp4"
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.

Waiting for 0 seconds, press a key to continue ...

C:\Users\Dani Marion\Desktop>(
echo 3
 storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*
 TIMEOUT 2
)
3
 [Sun Sep 25 2016 23:08:57 GMT+0200 (W. Europe Daylight Time)] [warn]   A redundancy of 0 means files will not be mirrored!
 [Sun Sep 25 2016 23:08:57 GMT+0200 (W. Europe Daylight Time)] [info]   30 file(s) to upload.
 [Sun Sep 25 2016 23:08:59 GMT+0200 (W. Europe Daylight Time)] [info]   Generating encryption key...
 [Sun Sep 25 2016 23:09:00 GMT+0200 (W. Europe Daylight Time)] [info]   Encrypting file "D:/films/A.Promise.2013.720p.BluRay.x264.YIFY.mp4"

Waiting for 0 seconds, press a key to continue ...

C:\Users\Dani Marion\Desktop>(
echo 4
 storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*
 TIMEOUT 2
)
4
 [Sun Sep 25 2016 23:09:44 GMT+0200 (W. Europe Daylight Time)] [warn]   A redundancy of 0 means files will not be mirrored!
 [Sun Sep 25 2016 23:09:45 GMT+0200 (W. Europe Daylight Time)] [info]   30 file(s) to upload.
 [Sun Sep 25 2016 23:09:47 GMT+0200 (W. Europe Daylight Time)] [info]   Generating encryption key...
 [Sun Sep 25 2016 23:09:47 GMT+0200 (W. Europe Daylight Time)] [info]   Encrypting file "D:/films/A.Promise.2013.720p.BluRay.x264.YIFY.mp4"
 [Sun Sep 25 2016 23:11:18 GMT+0200 (W. Europe Daylight Time)] [info]   [ A.Promise.2013.720p.BluRay.x264.YIFY.mp4 ] Encryption complete
 [Sun Sep 25 2016 23:11:19 GMT+0200 (W. Europe Daylight Time)] [info]   [ A.Promise.2013.720p.BluRay.x264.YIFY.mp4 ] Creating storage token... (retry: 0)
 [Sun Sep 25 2016 23:11:19 GMT+0200 (W. Europe Daylight Time)] [info]   [ A.Promise.2013.720p.BluRay.x264.YIFY.mp4 ] Storing file, hang tight!
 [Sun Sep 25 2016 23:11:20 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard E:\Upload\temp\33c3681070bf index 0
 [Sun Sep 25 2016 23:11:28 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard E:\Upload\temp\5f071bbd6dbf index 1
 [Sun Sep 25 2016 23:11:28 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: a40ca0dc50c8b1eceda8ab62dbb147c18d6d486b
 [Sun Sep 25 2016 23:11:35 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Sun Sep 25 2016 23:11:35 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Sun Sep 25 2016 23:11:35 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for a40ca0dc50c8b1eceda8ab62dbb147c18d6d486b (retry: 0)
 [Sun Sep 25 2016 23:11:37 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard E:\Upload\temp\97b63bb855d0 index 2
 [Sun Sep 25 2016 23:11:37 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: fdfca589d30a62b449c6ab2415501fb4c0356c38
 [Sun Sep 25 2016 23:11:43 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Sun Sep 25 2016 23:11:44 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Sun Sep 25 2016 23:11:44 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for fdfca589d30a62b449c6ab2415501fb4c0356c38 (retry: 0)
 [Sun Sep 25 2016 23:11:50 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard E:\Upload\temp\7ca9af687fbd index 3
 [Sun Sep 25 2016 23:11:50 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 989e65a39ff109efb98a451dd75d8a92e4e66195
 [Sun Sep 25 2016 23:11:57 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Sun Sep 25 2016 23:11:57 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Sun Sep 25 2016 23:11:57 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 989e65a39ff109efb98a451dd75d8a92e4e66195 (retry: 0)
 [Sun Sep 25 2016 23:12:02 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.1","address":"193.95.242.159","port":11951,"nodeID
":"92b3cd9634077f37886899903420996f0307a406","lastSeen":1474837916950}
 [Sun Sep 25 2016 23:12:02 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Sun Sep 25 2016 23:12:07 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard E:\Upload\temp\17679d271702 index 4
 [Sun Sep 25 2016 23:12:07 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 40a20af47fa6888590c56bb762664e87e2f56c57
 [Sun Sep 25 2016 23:12:16 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard E:\Upload\temp\401fc2c05c75 index 5
 [Sun Sep 25 2016 23:12:16 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: a0e52398a06d454b8cf461ff0341b508ed337b92
 [Sun Sep 25 2016 23:12:21 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Sun Sep 25 2016 23:12:21 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Sun Sep 25 2016 23:12:21 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for a0e52398a06d454b8cf461ff0341b508ed337b92 (retry: 0)
 [Sun Sep 25 2016 23:12:29 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.1","address":"neomark.go.ro","port":4060,"nodeID":
"64f012aa782ae9234b5fce664ff6ce173d82b5c1","lastSeen":1474837943649}
 [Sun Sep 25 2016 23:12:29 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Sun Sep 25 2016 23:12:36 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Sun Sep 25 2016 23:12:36 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Sun Sep 25 2016 23:12:36 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 40a20af47fa6888590c56bb762664e87e2f56c57 (retry: 0)
 [Sun Sep 25 2016 23:12:37 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 9baafdc660547fa7fc245a808cc8155e94ed90a2
 [Sun Sep 25 2016 23:12:53 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Sun Sep 25 2016 23:12:53 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Sun Sep 25 2016 23:12:53 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 9baafdc660547fa7fc245a808cc8155e94ed90a2 (retry: 0)
 [Sun Sep 25 2016 23:12:57 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.1","address":"74.56.126.24","port":42721,"nodeID":
"b7f0f7ab47c63e2f9ed59fbbe2e1146289a348b4","lastSeen":1474837972368}
 [Sun Sep 25 2016 23:12:58 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
buffer.js:25
    const ui8 = new Uint8Array(size);
                ^

RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at createBuffer (buffer.js:25:17)
    at allocate (buffer.js:158:12)
    at new Buffer (buffer.js:56:12)
    at Function.Buffer.concat (buffer.js:286:16)
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\storj-lib\node_modules\ws\lib\PerMessageDeflate.js:309:23
    at afterWrite (_stream_writable.js:354:3)
    at onwrite (_stream_writable.js:345:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:625:5)

Waiting for 0 seconds, press a key to continue ...

C:\Users\Dani Marion\Desktop>(
echo 5
 storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*
 TIMEOUT 2
)
5
 [Sun Sep 25 2016 23:14:09 GMT+0200 (W. Europe Daylight Time)] [warn]   A redundancy of 0 means files will not be mirrored!
 [Sun Sep 25 2016 23:14:09 GMT+0200 (W. Europe Daylight Time)] [info]   30 file(s) to upload.
```

**Comment by 1credit** [comment]
Augmenting this note.    It is still occuring as of:

fspoe home # npm list -g storj
/usr/lib64
âââ storj@4.0.1
fspoe home # storj --version
Storjcli: 1.0.11 | Core: 4.0.2

Tested with a 14GB file that consumed 14GB of memory during the upload attempt.

**Comment by littleskunk** [comment]
Please try to update your node version to 4.6.0 and try again. I have read about memory bugs in different nodejs versions.

**Comment by CJClaude** [comment]
Note this problem still existing at;

StorjShare: 8.0.0
Core:       5.1.2
Protocol:   0.10.0
Node:     6.9.1

http://puu.sh/syVk8/7452fe835f.png

The above was captured while uploading a 27GB tarball:

-rw-r--r-- 1 root root 28639899012 Nov 29 18:12 backup.tar.crypt

Memory usage was fine during the encryption stage and skyrockted within seconds of the first data channel being opened.

**Comment by bookchin** [comment]
Data channels have problems, let's circle back here after the storj-lib6 release upcoming which completely removes them in favor of a simpler and more elegant strategy.

**Comment by CJClaude** [comment]
Acknowledged.  Will keep the identical test case available.  Aborting current test that managed to send about 10 shards over 9+ hours (about 20% of available bandwidth).

**Comment by CJClaude** [comment]
Tested against Staging:

Storjcli: 3.0.0 | Core: 6.0.1

25080 root      20   0 27.404g 0.025t  10444 S   7.0 81.3   2:23.23 node

i5serv storj-25080Khsx7UDxL1dc # ls -l
total 27968656
-rw-r--r-- 1 root root 28639899012 Dec  2 19:45 backup.tar.crypt

So the problem still exist.  This will limit people to uploading file no larger than a significant fraction of their memory size, unless they can tollerate heavy swapping, but even then its limited.

**Comment by bookchin** [comment]
https://github.com/Storj/core/issues/656
