### ISSUE TITLE
if (fn === null) throw new Error("Callback was already called.");

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#427]
### Package Versions

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core

storj  --version 3.2.0
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

upload successful

### Command
```
storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*
```
### Actual Behavior

```
 [Wed Sep 14 2016 23:31:41 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 0ed8af5c26f5e99da4938ad221d737f91575a907
 [Wed Sep 14 2016 23:31:44 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Wed Sep 14 2016 23:31:44 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Wed Sep 14 2016 23:31:44 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 0ed8af5c26f5e99da4938ad221d737f91575a907 (retry: 0)
 [Wed Sep 14 2016 23:31:51 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 9b1b586759e999c5e42c231ef8b287081ae0c528 (retry: 3)
 [Wed Sep 14 2016 23:32:59 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 9714edfc80fa9ee7efc0ccc59044801f197e211e (retry: 2)
 [Wed Sep 14 2016 23:33:30 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 12 remaining...
 [Wed Sep 14 2016 23:33:30 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\082521302be5 index 13
 [Wed Sep 14 2016 23:33:31 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 11 remaining...
C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\async\lib\async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\async\lib\async.js:43:36
    at BridgeClient._shardTransferComplete (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:611:3)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:666:11)
    at emitNone (events.js:72:20)
    at WritableDataChannelStream.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\flushwritable\lib\FlushWritable.js:32:33)

    at WebSocket.WritableDataChannelStream._handleClosed (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\data-channels\writable-stream.js:154:3
)
    at WebSocket._flush (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\data-channels\writable-stream.js:87:24)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at WebSocket.cleanupWebsocketResources (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\ws\lib\WebSocket.js:950:8)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)

C:\Windows\system32>
```

### Steps to Reproduce

upload files in a directory

**Comment by wanyuehan** [comment]
There is the same issue in Node Open Mining portal.because it not specified  the async's version in package.json.
When i specified  the version of async to 1.5.2, problem solved.
I hope this information is helpful to you.

**Comment by bookchin** [comment]
We are on 1.5.2: https://github.com/Storj/core/blob/master/package.json

**Comment by MeijeSibbel** [comment]
This issue also surfaces in the pre-release versions every few uploads.

**Comment by bookchin** [comment]
@aleitner did I see a PR merged that closes this?
