### ISSUE TITLE
Callback was already called error

### ISSUE THREAD

**Issue by 1credit** [Storj/core#448]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj 4.0.0-beta
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

Uploads work.
```

```

### Actual Behavior
``
` [Wed Sep 21 2016 13:32:48 GMT-0500 (CDT)] [info]   Shard transfer completed! 350 remaining...
 [Wed Sep 21 2016 13:32:48 GMT-0500 (CDT)] [info]   Trying to upload shard /tmp/254950dcfac3 index 171
 [Wed Sep 21 2016 13:32:49 GMT-0500 (CDT)] [info]   Hash for this shard is: 8ef493de19733170ae0b43d2c84a405d25a6cd77
 [Wed Sep 21 2016 13:32:50 GMT-0500 (CDT)] [info]   Audit generation for shard done.
 [Wed Sep 21 2016 13:32:50 GMT-0500 (CDT)] [info]   Waiting on a storage offer from the network...
 [Wed Sep 21 2016 13:32:50 GMT-0500 (CDT)] [info]   Querying bridge for contract for 8ef493de19733170ae0b43d2c84a405d25a6cd77 (retry: 0)
 [Wed Sep 21 2016 13:32:52 GMT-0500 (CDT)] [info]   Contract negotiated with: {"protocol":"0.8.1","address":"puychip.no-ip.biz","port":5000,"nodeID":"957e6f0e7af02961b13d27d2cda1aa55ed92a840","lastSeen":1474482771428}
 [Wed Sep 21 2016 13:32:53 GMT-0500 (CDT)] [info]   Data channel opened, transferring shard...
 [Wed Sep 21 2016 13:33:16 GMT-0500 (CDT)] [info]   Shard transfer completed! 349 remaining...
 [Wed Sep 21 2016 13:33:16 GMT-0500 (CDT)] [info]   Trying to upload shard /tmp/11b88d6c427e index 172
 [Wed Sep 21 2016 13:33:17 GMT-0500 (CDT)] [info]   Hash for this shard is: c9964f55eb5f5e42f2eb5b47a09844adfcfa8c39
 [Wed Sep 21 2016 13:33:18 GMT-0500 (CDT)] [info]   Audit generation for shard done.
 [Wed Sep 21 2016 13:33:18 GMT-0500 (CDT)] [info]   Waiting on a storage offer from the network...
 [Wed Sep 21 2016 13:33:18 GMT-0500 (CDT)] [info]   Querying bridge for contract for c9964f55eb5f5e42f2eb5b47a09844adfcfa8c39 (retry: 0)
 [Wed Sep 21 2016 13:33:19 GMT-0500 (CDT)] [info]   Contract negotiated with: {"protocol":"0.8.1","address":"46.30.41.195","port":5000,"nodeID":"d65921bfb19f696647d530a8c624c647e3a4bfea","lastSeen":1474482799236}
 [Wed Sep 21 2016 13:33:20 GMT-0500 (CDT)] [info]   Data channel opened, transferring shard...
 [Wed Sep 21 2016 13:34:07 GMT-0500 (CDT)] [info]   Querying bridge for contract for 238bd939035014ce7f8d22be083b2ad5b3aeaed4 (retry: 2)
 [Wed Sep 21 2016 13:34:29 GMT-0500 (CDT)] [info]   Shard transfer completed! 348 remaining...
/usr/lib64/node_modules/storj/node_modules/storj-lib/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /usr/lib64/node_modules/storj/node_modules/storj-lib/node_modules/async/lib/async.js:43:36
    at BridgeClient._shardTransferComplete (/usr/lib64/node_modules/storj/node_modules/storj-lib/lib/bridge-client/index.js:611:3)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (/usr/lib64/node_modules/storj/node_modules/storj-lib/lib/bridge-client/index.js:667:11)
    at emitNone (events.js:72:20)
    at WritableDataChannelStream.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (/usr/lib64/node_modules/storj/node_modules/storj-lib/node_modules/flushwritable/lib/FlushWritable.js:32:33)
    at WebSocket.WritableDataChannelStream._handleClosed (/usr/lib64/node_modules/storj/node_modules/storj-lib/lib/data-channels/writable-stream.js:154:3)
    at WebSocket._flush (/usr/lib64/node_modules/storj/node_modules/storj-lib/lib/data-channels/writable-stream.js:87:24)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at WebSocket.cleanupWebsocketResources (/usr/lib64/node_modules/storj/node_modules/storj-lib/node_modules/ws/lib/WebSocket.js:950:8)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
fspoe store #
`

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by bookchin** [comment]
Can you reopen here: https://github.com/Storj/core-cli/issues
