### ISSUE TITLE
const ui8 = new Uint8Array(size);

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#451]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core

storj --version -> 1.0.1

```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

Shard size is calculated based on computer resources, upload starts without any issues.

### Actual Behavior

```
[Thu Sep 22 2016 19:55:30 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Thu Sep 22 2016 19:55:40 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Thu Sep 22 2016 19:55:40 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Thu Sep 22 2016 19:55:40 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for e912211682a5ef0bbc4c0ce61018eeb05ce
d0b13 (retry: 0)
buffer.js:25
    const ui8 = new Uint8Array(size);
                ^

RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at createBuffer (buffer.js:25:17)
    at allocate (buffer.js:158:12)
    at new Buffer (buffer.js:56:12)
    at allocNewPool (fs.js:1602:10)
    at ReadStream._read (fs.js:1701:5)
    at ReadStream.Readable.read (_stream_readable.js:336:10)
    at readableAddChunk (_stream_readable.js:154:18)
    at ReadStream.Readable.push (_stream_readable.js:111:10)
    at onread (fs.js:1739:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)

C:\Users\Dani Marion>
```

### Steps to Reproduce

Upload a 20GB file on a PC with 2GB RAM running windows 8.1.

**Comment by aleitner** [comment]
Just out of curiosity have any of the shards been uploaded at the point that you are seeing this error?

**Comment by MeijeSibbel** [comment]
Here is the complete log @aleitner :

```
C:\Users\Dani Marion>storj -k meije0612 upload-file 57af3a1e8f266a7d4e391055 D:\20GB
 [Fri Sep 23 2016 22:21:58 GMT+0200 (W. Europe Daylight Time)] [warn]   A redundancy of 0 means files will not be mirrored!
 [Fri Sep 23 2016 22:21:58 GMT+0200 (W. Europe Daylight Time)] [info]   1 file(s) to upload.
 [Fri Sep 23 2016 22:22:00 GMT+0200 (W. Europe Daylight Time)] [info]   Generating encryption key...
 [Fri Sep 23 2016 22:22:00 GMT+0200 (W. Europe Daylight Time)] [info]   Encrypting file "D:/20GB"
 [Fri Sep 23 2016 22:52:53 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Encryption complete
 [Fri Sep 23 2016 22:52:53 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Creating storage token... (retry: 0)
 [Fri Sep 23 2016 22:52:53 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Storing file, hang tight!
 [Fri Sep 23 2016 22:52:54 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\c44e741a7da5 index 0
 [Fri Sep 23 2016 22:53:02 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\f15ff3ffcc0b index 1
 [Fri Sep 23 2016 22:53:02 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 7282401c71a551aed6c4e16caf5252c468861b66
 [Fri Sep 23 2016 22:53:18 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\a8ab016517a9 index 2
 [Fri Sep 23 2016 22:53:18 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 2bcd12de64d2599ad478c91d39913487f2397893
 [Fri Sep 23 2016 22:53:18 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Fri Sep 23 2016 22:53:18 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Fri Sep 23 2016 22:53:18 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 7282401c71a551aed6c4e16caf5252c4688
61b66 (retry: 0)
 [Fri Sep 23 2016 22:53:22 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"userAgent":"3.1.2","protocol":"0.8.1","a
ddress":"STORJ-CLUS-003.storj.space","port":4000,"nodeID":"2b670a0eaa3076c84734af4902b2fc42dda8f0e9","lastSeen":1474663998339}
 [Fri Sep 23 2016 22:53:22 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Fri Sep 23 2016 22:53:33 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\ce03d4422238 index 3
 [Fri Sep 23 2016 22:53:33 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 50d710ce00624e952f122dfec669c6029bcc1adb
 [Fri Sep 23 2016 22:53:33 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Fri Sep 23 2016 22:53:33 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Fri Sep 23 2016 22:53:33 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 2bcd12de64d2599ad478c91d39913487f23
97893 (retry: 0)
 [Fri Sep 23 2016 22:53:35 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"userAgent":"3.2.3","protocol":"0.8.1","a
ddress":"foximulder.awinet.at","port":4000,"nodeID":"3f063e270479c5bb9c146507ebda3c9ae432384b","lastSeen":1474664012653}
 [Fri Sep 23 2016 22:53:36 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Fri Sep 23 2016 22:53:49 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\24e323226f6d index 4
 [Fri Sep 23 2016 22:53:49 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 90a7c4097b860cb43ce78530e2772b9f0c3623ec
 [Fri Sep 23 2016 22:53:49 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Fri Sep 23 2016 22:53:49 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Fri Sep 23 2016 22:53:49 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 50d710ce00624e952f122dfec669c6029bc
c1adb (retry: 0)
 [Fri Sep 23 2016 22:54:04 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\c92111f3a0f1 index 5
 [Fri Sep 23 2016 22:54:04 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: df8f931f208584d1a03e17a08f6f4497f4e75542
 [Fri Sep 23 2016 22:54:04 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Fri Sep 23 2016 22:54:04 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Fri Sep 23 2016 22:54:04 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 90a7c4097b860cb43ce78530e2772b9f0c3
623ec (retry: 0)
 [Fri Sep 23 2016 22:54:04 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 50d710ce00624e952f122dfec669c6029bc
c1adb (retry: 1)
 [Fri Sep 23 2016 22:54:19 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Fri Sep 23 2016 22:54:19 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Fri Sep 23 2016 22:54:19 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for df8f931f208584d1a03e17a08f6f4497f4e
75542 (retry: 0)
 [Fri Sep 23 2016 22:54:19 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: f952e74d8940302f1678ca24b7a635d8f43f19f4
 [Fri Sep 23 2016 22:54:35 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Fri Sep 23 2016 22:54:35 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Fri Sep 23 2016 22:54:35 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for f952e74d8940302f1678ca24b7a635d8f43
f19f4 (retry: 0)
 [Fri Sep 23 2016 22:54:40 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"userAgent":"3.2.3","protocol":"0.8.1","a
ddress":"foximulder.awinet.at","port":4000,"nodeID":"3f063e270479c5bb9c146507ebda3c9ae432384b","lastSeen":1474664075029}
 [Fri Sep 23 2016 22:54:40 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
buffer.js:25
    const ui8 = new Uint8Array(size);
                ^

RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at createBuffer (buffer.js:25:17)
    at allocate (buffer.js:158:12)
    at new Buffer (buffer.js:56:12)
    at allocNewPool (fs.js:1602:10)
    at ReadStream._read (fs.js:1701:5)
    at ReadStream.Readable.read (_stream_readable.js:336:10)
    at readableAddChunk (_stream_readable.js:154:18)
    at ReadStream.Readable.push (_stream_readable.js:111:10)
    at onread (fs.js:1739:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)

C:\Users\Dani Marion>

```
