### ISSUE TITLE
Failure to install latest pre-release

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#460]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core

Storj -> 1.0.1
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

```
Installation succesfull
```

### Actual Behavior

```
C:\Users\Dani Marion>npm install -g storj@next
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
|
> leveldown@1.4.6 install C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\leveldown
> prebuild --install

prebuild WARN install No prebuilt binaries found (target=v4.5.0 arch=ia32 platform=win32)
C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\leveldown\node_modules\prebuild\node_modules
\node-gyp\node_modules\graceful-fs\polyfills.js:264
      if (stats.uid < 0) stats.uid += 0x100000000
               ^

TypeError: Cannot read property 'uid' of undefined
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\leveldown\node_modules\prebuild\node_
modules\node-gyp\node_modules\graceful-fs\polyfills.js:264:16
    at FSReqWrap.oncomplete (fs.js:82:15)
 npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "storj@ne
xt"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.4.6 install: `prebuild --install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.4.6 install script 'prebuild --install'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Dani Marion\npm-debug.log

C:\Users\Dani Marion>


```

### Steps to Reproduce

Update storj to latest pre-release

**Comment by MeijeSibbel** [comment]
```
C:\Users\Meije>npm install storj-lib --save
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> leveldown@1.4.6 install C:\Users\Meije\node_modules\leveldown
> prebuild --install

prebuild WARN install No prebuilt binaries found (target=v6.3.1 arch=x64 platform=win32)
C:\Users\Meije\node_modules\graceful-fs\polyfills.js:264
      if (stats.uid < 0) stats.uid += 0x100000000
               ^

TypeError: Cannot read property 'uid' of undefined
    at C:\Users\Meije\node_modules\graceful-fs\polyfills.js:264:16
    at FSReqWrap.oncomplete (fs.js:123:15)
C:\Users\Meije
+-- bitcore-ecies@1.0.1
| `-- aes@0.1.0
+-- bitcore-message@1.0.2
| `-- bitcore-lib@0.13.19
|   +-- bn.js@2.0.4
|   +-- bs58@2.0.0
|   +-- buffer-compare@1.0.0
|   +-- elliptic@3.0.3
|   | +-- brorand@1.0.5
|   | `-- hash.js@1.0.3
|   +-- inherits@2.0.1
|   `-- lodash@3.10.1
+-- d@0.1.1
| `-- es5-ext@0.10.12
|   +-- es6-iterator@2.0.0
|   `-- es6-symbol@3.1.0
+-- flushwritable@1.0.0
+-- ip@1.1.3
+-- jsen@0.6.3
+-- json-stable-stringify@1.0.1
| `-- jsonify@0.0.0
+-- kad-logger-json@0.1.2
| +-- chai@3.5.0
| | +-- assertion-error@1.0.2
| | +-- deep-eql@0.1.3
| | | `-- type-detect@0.1.1
| | `-- type-detect@1.0.0
| `-- readable-stream@2.1.5
|   +-- buffer-shims@1.0.0
|   +-- core-util-is@1.0.2
|   +-- inherits@2.0.3
|   +-- isarray@1.0.0
|   +-- process-nextick-args@1.0.7
|   +-- string_decoder@0.10.31
|   `-- util-deprecate@1.0.2
+-- kad-quasar@0.2.1
| +-- bloem@0.2.4
| | +-- bitbuffer@0.1.3
| | `-- fnv@0.1.3
| +-- kad@1.5.18
| | +-- async@0.9.2
| | +-- clarinet@0.11.0
| | +-- colors@1.1.2
| | +-- hat@0.0.3
| | +-- kad-fs@0.0.4
| | +-- kad-localstorage@0.0.7
| | | `-- dom-storage@2.0.2
| | +-- kad-memstore@0.0.1
| | `-- lodash@3.10.1
| `-- merge@1.2.0
+-- knuth-shuffle@1.0.1
+-- levelup@1.3.2
| +-- deferred-leveldown@1.2.1
| | `-- abstract-leveldown@2.4.1
| +-- level-codec@6.1.0
| +-- level-errors@1.0.4
| | `-- errno@0.1.4
| |   `-- prr@0.0.0
| +-- level-iterator-stream@1.3.1
| | `-- readable-stream@1.1.14
| |   `-- isarray@0.0.1
| +-- prr@1.0.1
| +-- semver@5.1.1
| `-- xtend@4.0.1
+-- mime@1.3.4
+-- mtree@0.0.1
+-- nat-upnp@1.0.3
| +-- async@0.1.22
| +-- ip@0.0.5
| +-- request@2.74.0
| | +-- bl@1.1.2
| | | `-- readable-stream@2.0.6
| | `-- form-data@1.0.1
| |   `-- async@2.0.1
| |     `-- lodash@4.16.2
| `-- xml2js@0.1.14
|   `-- sax@1.2.1
+-- node-tar.gz@1.0.0
| +-- bluebird@2.11.0
| +-- commander@2.9.0
| | `-- graceful-readlink@1.0.1
| +-- fstream@1.0.10
| | +-- graceful-fs@4.1.7
| | `-- rimraf@2.5.4
| |   `-- glob@7.1.0
| |     +-- fs.realpath@1.0.0
| |     +-- inflight@1.0.5
| |     | `-- wrappy@1.0.2
| |     +-- minimatch@3.0.3
| |     | `-- brace-expansion@1.1.6
| |     |   +-- balanced-match@0.4.2
| |     |   `-- concat-map@0.0.1
| |     +-- once@1.4.0
| |     `-- path-is-absolute@1.0.0
| +-- mocha@2.5.3
| | +-- commander@2.3.0
| | +-- diff@1.4.0
| | +-- escape-string-regexp@1.0.2
| | +-- glob@3.2.11
| | | `-- minimatch@0.3.0
| | |   +-- lru-cache@2.7.3
| | |   `-- sigmund@1.0.1
| | +-- growl@1.9.2
| | +-- jade@0.26.3
| | | +-- commander@0.6.1
| | | `-- mkdirp@0.3.0
| | +-- supports-color@1.2.0
| | `-- to-iso-string@0.0.2
| +-- mout@0.11.1
| `-- tar@2.2.1
|   `-- block-stream@0.0.9
+-- ntp-client@0.5.4  (git://github.com/bookchin/node-ntp-client.git#4eb7ffa659596d9ea23a3fdc10f3355112efb811)
+-- portfinder@1.0.7
| +-- async@1.5.2
| +-- debug@2.2.0
| | `-- ms@0.7.1
| `-- mkdirp@0.5.1
|   `-- minimist@0.0.8
+-- request@2.75.0
| +-- aws-sign2@0.6.0
| +-- aws4@1.4.1
| +-- bl@1.1.2
| | `-- readable-stream@2.0.6
| +-- caseless@0.11.0
| +-- combined-stream@1.0.5
| | `-- delayed-stream@1.0.0
| +-- extend@3.0.0
| +-- forever-agent@0.6.1
| +-- form-data@2.0.0
| | `-- asynckit@0.4.0
| +-- har-validator@2.0.6
| | +-- chalk@1.1.3
| | | +-- ansi-styles@2.2.1
| | | +-- escape-string-regexp@1.0.5
| | | +-- has-ansi@2.0.0
| | | | `-- ansi-regex@2.0.0
| | | +-- strip-ansi@3.0.1
| | | `-- supports-color@2.0.0
| | +-- is-my-json-valid@2.14.0
| | | +-- generate-function@2.0.0
| | | +-- generate-object-property@1.2.0
| | | | `-- is-property@1.0.2
| | | `-- jsonpointer@2.0.0
| | `-- pinkie-promise@2.0.1
| |   `-- pinkie@2.0.4
| +-- hawk@3.1.3
| | +-- boom@2.10.1
| | +-- cryptiles@2.0.5
| | +-- hoek@2.16.3
| | `-- sntp@1.0.9
| +-- http-signature@1.1.1
| | +-- assert-plus@0.2.0
| | +-- jsprim@1.3.1
| | | +-- extsprintf@1.0.2
| | | +-- json-schema@0.2.3
| | | `-- verror@1.3.6
| | `-- sshpk@1.10.0
| |   +-- asn1@0.2.3
| |   +-- assert-plus@1.0.0
| |   +-- bcrypt-pbkdf@1.0.0
| |   | `-- tweetnacl@0.14.3
| |   +-- dashdash@1.14.0
| |   | `-- assert-plus@1.0.0
| |   +-- ecc-jsbn@0.1.1
| |   +-- getpass@0.1.6
| |   | `-- assert-plus@1.0.0
| |   +-- jodid25519@1.0.2
| |   +-- jsbn@0.1.0
| |   `-- tweetnacl@0.13.3
| +-- is-typedarray@1.0.0
| +-- isstream@0.1.2
| +-- json-stringify-safe@5.0.1
| +-- mime-types@2.1.12
| | `-- mime-db@1.24.0
| +-- node-uuid@1.4.7
| +-- oauth-sign@0.8.2
| +-- qs@6.2.1
| +-- stringstream@0.0.5
| +-- tough-cookie@2.3.1
| `-- tunnel-agent@0.4.3
+-- semver@5.3.0
+-- through@2.3.8
+-- tmp@0.0.28
| `-- os-tmpdir@1.0.1
`-- ws@1.1.1
  +-- options@0.0.6
  `-- ultron@1.0.2

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Meije\package.json'
npm WARN Meije No description
npm WARN Meije No repository field.
npm WARN Meije No README data
npm WARN Meije No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "storj-lib" "--save"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.4.6 install: `prebuild --install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.4.6 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Meije\npm-debug.log

C:\Users\Meije>
```

**Comment by MeijeSibbel** [comment]
Suddenly it started is working.
