### ISSUE TITLE
const ui8 = new Uint8Array(size);

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#462]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core

Storj -> v4.0.0-rc.5 (hotfix)
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

```
Upload continues. 
```

### Actual Behavior

```
 storj -k meije0612 -c 1 upload-file 57af3a1e8f266a7d4e391055 D:\20GB
 TIMEOUT 2
)
17
 [Tue Sep 27 2016 10:03:11 GMT+0200 (W. Europe Daylight Time)] [warn]   A redundancy of 0 means files will not be mirrored!
 [Tue Sep 27 2016 10:03:11 GMT+0200 (W. Europe Daylight Time)] [info]   1 file(s) to upload.
 [Tue Sep 27 2016 10:03:13 GMT+0200 (W. Europe Daylight Time)] [info]   Generating encryption key...
 [Tue Sep 27 2016 10:03:13 GMT+0200 (W. Europe Daylight Time)] [info]   Encrypting file "D:/20GB"
 [Tue Sep 27 2016 10:30:03 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Encryption complete
 [Tue Sep 27 2016 10:30:03 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Creating storage token... (retry: 0)
 [Tue Sep 27 2016 10:30:04 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Storing file, hang tight!
 [Tue Sep 27 2016 10:30:06 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\e9bee09d9f29 index 0
 [Tue Sep 27 2016 10:30:54 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: f9ef4341749afa6ce131aaf44768552f3ee78987
 [Tue Sep 27 2016 10:32:36 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Tue Sep 27 2016 10:32:36 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Tue Sep 27 2016 10:32:36 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for f9ef4341749afa6ce131aaf44768552f3ee78987 (retry: 0)
 [Tue Sep 27 2016 10:32:40 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for f9ef4341749afa6ce131aaf44768552f3ee78987 (retry: 1)
 [Tue Sep 27 2016 10:32:43 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for f9ef4341749afa6ce131aaf44768552f3ee78987 (retry: 2)
 [Tue Sep 27 2016 10:32:46 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for f9ef4341749afa6ce131aaf44768552f3ee78987 (retry: 3)
 [Tue Sep 27 2016 10:32:49 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for f9ef4341749afa6ce131aaf44768552f3ee78987 (retry: 4)
 [Tue Sep 27 2016 10:32:56 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for f9ef4341749afa6ce131aaf44768552f3ee78987 (retry: 5)
buffer.js:25
    const ui8 = new Uint8Array(size);
                ^

RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at createBuffer (buffer.js:25:17)
    at allocate (buffer.js:158:12)
    at new Buffer (buffer.js:56:12)
    at allocNewPool (fs.js:1602:10)
    at ReadStream._read (fs.js:1701:5)
    at ReadStream.Readable.read (_stream_readable.js:336:10)
    at readableAddChunk (_stream_readable.js:154:18)
    at ReadStream.Readable.push (_stream_readable.js:111:10)
    at onread (fs.js:1739:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)

Waiting for 0 seconds, press a key to continue ...
```

### Steps to Reproduce

Upload a large file, 20GB.

**Comment by aleitner** [comment]
You're running out of memory before you even transfer a shard!

**Comment by MeijeSibbel** [comment]
Is that because the encryption phase consumes to much memory?, i can run 5-7x upload instances simultaneously with 1-2 GB files without any issues.

**Comment by aleitner** [comment]
Closed by this commit https://github.com/Storj/core-cli/commit/dfee0f9569739fb3397b9ea0b0f3a66a106d57c4 Until we can figure out a better way for memory management
