### ISSUE TITLE
if (fn === null) throw new Error("Callback was already called.");

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#475]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core

storj --version: 1.0.9
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

```
Upload continues.
```

### Actual Behavior

```
 [Thu Sep 29 2016 15:16:08 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Thu Sep 29 2016 15:16:08 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Thu Sep 29 2016 15:16:08 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Remote host terminated early
 [Thu Sep 29 2016 15:16:08 GMT+0200 (W. Europe Daylight Time)] [info]   Retrying shard transfer, pointer: {"hash":"20dc31045c4df33376929e17798be89930229d8d","token":
"a9f65ff9e17a7493a43dff175ba710784d53711c","operation":"PUSH","farmer":{"protocol":"0.8.1","address":"001s.storjlt.xyz","port":5000,"nodeID":"256c5496e366a6474454d4f
69eead171502deeae","lastSeen":1475154874253}}
 [Thu Sep 29 2016 15:16:08 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Remote host terminated early
 [Thu Sep 29 2016 15:16:08 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer failed 3 times, getting another contract...
 [Thu Sep 29 2016 15:16:08 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 20dc31045c4df33376929e17798be89930229d8d
 [Thu Sep 29 2016 15:16:08 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Thu Sep 29 2016 15:16:08 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Channel is already active
 [Thu Sep 29 2016 15:16:08 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Channel is already active
 [Thu Sep 29 2016 15:16:08 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Remote host terminated early
 [Thu Sep 29 2016 15:16:08 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to transfer shard, reason: Channel is already active
 [Thu Sep 29 2016 15:16:11 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Thu Sep 29 2016 15:16:11 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Thu Sep 29 2016 15:16:11 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 20dc31045c4df33376929e17798be89930229d8d (retry: 0)
 [Thu Sep 29 2016 15:16:13 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.1","address":"011c.storjlt.xyz","port":8201,"nodeI
D":"29b84886d9895dd8aec13ca09c2274ee336f22d1","lastSeen":1475154974214}
 [Thu Sep 29 2016 15:16:13 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Thu Sep 29 2016 15:16:50 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 16 remaining...
 [Thu Sep 29 2016 15:16:50 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\1c3a679be97c index 13
 [Thu Sep 29 2016 15:16:51 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: a634a586b4b6ff19776fc1df374f1ae33f56b189
 [Thu Sep 29 2016 15:16:54 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Thu Sep 29 2016 15:16:54 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Thu Sep 29 2016 15:16:54 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for a634a586b4b6ff19776fc1df374f1ae33f56b189 (retry: 0)
 [Thu Sep 29 2016 15:16:56 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.1","address":"veeit30163.dyndns.org","port":7040,"
nodeID":"a7b56d0714d305e78474ee5783898d37f1acba32","lastSeen":1475155017377}
 [Thu Sep 29 2016 15:16:56 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Thu Sep 29 2016 15:17:01 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 15 remaining...
 [Thu Sep 29 2016 15:17:01 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\ad5641ad4544 index 14
 [Thu Sep 29 2016 15:17:02 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: fdf20a14fc0b6e9466ad8e224884e2c792de014a
 [Thu Sep 29 2016 15:17:06 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Thu Sep 29 2016 15:17:06 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Thu Sep 29 2016 15:17:06 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for fdf20a14fc0b6e9466ad8e224884e2c792de014a (retry: 0)
 [Thu Sep 29 2016 15:17:07 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.1","address":"veeit30163.dyndns.org","port":7060,"
nodeID":"ed653a3c1b8cbb5a946c12bd8412af4abef74a55","lastSeen":1475155028844}
 [Thu Sep 29 2016 15:17:08 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Thu Sep 29 2016 15:17:13 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 14 remaining...
C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\async\lib\async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\async\lib\async.js:43:36
    at BridgeClient._shardTransferComplete (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:618:12)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:682:11)
    at emitNone (events.js:72:20)
    at WritableDataChannelStream.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\flushwritable\lib\Flush
Writable.js:32:33)
    at WebSocket.WritableDataChannelStream._handleClosed (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\data-channels\writab
le-stream.js:154:3)
    at WebSocket._flush (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\data-channels\writable-stream.js:87:24)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at WebSocket.cleanupWebsocketResources (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\ws\lib\WebSocket.js:950:8
)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)

Waiting for 0 seconds, press a key to continue ...

C:\Users\Dani Marion\Desktop>(
echo 2
 storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*
 TIMEOUT 2
)
2
 [Thu Sep 29 2016 15:17:36 GMT+0200 (W. Europe Daylight Time)] [warn]   A redundancy of 0 means files will not be mirrored!
 [Thu Sep 29 2016 15:17:36 GMT+0200 (W. Europe Daylight Time)] [info]   30 file(s) to upload.
 [Thu Sep 29 2016 15:17:38 GMT+0200 (W. Europe Daylight Time)] [info]   Generating encryption key...
```

### Steps to Reproduce

Upload a file

**Comment by MeijeSibbel** [comment]
Same issue as: https://github.com/Storj/core/issues/427

**Comment by MeijeSibbel** [comment]
```
C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\async\lib\async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\async\lib\async.js:43:36
    at BridgeClient._shardTransferComplete (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:618:12)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:682:11)
    at emitNone (events.js:72:20)
    at WritableDataChannelStream.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\flushwritable\lib\Flush
Writable.js:32:33)
    at WebSocket.WritableDataChannelStream._handleClosed (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\data-channels\writab
le-stream.js:154:3)
    at WebSocket._flush (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\data-channels\writable-stream.js:87:24)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at WebSocket.cleanupWebsocketResources (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\ws\lib\WebSocket.js:950:8
)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)

C:\Users\Dani Marion\Desktop>(
echo 11
 storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*  1>>C:\StorjUpload.log
)
11
C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\async\lib\async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\async\lib\async.js:43:36
    at BridgeClient._shardTransferComplete (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:641:10)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:682:11)
    at emitNone (events.js:72:20)
    at WritableDataChannelStream.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\flushwritable\lib\Flush
Writable.js:32:33)
    at WebSocket.WritableDataChannelStream._handleClosed (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\data-channels\writab
le-stream.js:154:3)
    at WebSocket._flush (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\data-channels\writable-stream.js:87:24)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at WebSocket.cleanupWebsocketResources (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\ws\lib\WebSocket.js:950:8
)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)

C:\Users\Dani Marion\Desktop>(
echo 12
 storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*  1>>C:\StorjUpload.log
)
12

C:\Users\Dani Marion\Desktop>(
echo 13
 storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*  1>>C:\StorjUpload.log
)
13
fs.js:758
  return binding.rmdir(pathModule._makeLong(path));
                 ^

Error: ENOTEMPTY: directory not empty, rmdir 'D:\temp\storj-4596M20inpJkdHVS'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at _rmdirRecursiveSync (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:285:10)
    at _cleanupCallback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:409:5)
    at Uploader._cleanup (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:120:3)
    at Uploader._handleFailure (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:360:10)
    at null.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:383:10)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Monitor.sendEvent (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\os-monitor\os-monitor.js:72:8)
    at cycle (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\os-monitor\os-monitor.js:116:12)
    at wrapper (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

C:\Users\Dani Marion\Desktop>(
echo 14
 storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*  1>>C:\StorjUpload.log
)
14

C:\Users\Dani Marion\Desktop>(
echo 15
 storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*  1>>C:\StorjUpload.log
)
15

C:\Users\Dani Marion\Desktop>(
echo 16
 storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*  1>>C:\StorjUpload.log
)
16

C:\Users\Dani Marion\Desktop>(
echo 17
 storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*  1>>C:\StorjUpload.log
)
17
fs.js:758
  return binding.rmdir(pathModule._makeLong(path));
                 ^

Error: ENOTEMPTY: directory not empty, rmdir 'D:\temp\storj-2332AU9i8faQzews'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at _rmdirRecursiveSync (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:285:10)
    at _cleanupCallback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:409:5)
    at Uploader._cleanup (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:120:3)
    at Uploader._handleFailure (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:360:10)
    at null.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:383:10)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Monitor.sendEvent (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\os-monitor\os-monitor.js:72:8)
    at cycle (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\os-monitor\os-monitor.js:116:12)
    at wrapper (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

C:\Users\Dani Marion\Desktop>(
echo 18
 storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*  1>>C:\StorjUpload.log
)
18
C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\async\lib\async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\async\lib\async.js:43:36
    at BridgeClient._shardTransferComplete (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:618:12)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:682:11)
    at emitNone (events.js:72:20)
    at WritableDataChannelStream.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\flushwritable\lib\Flush
Writable.js:32:33)
    at WebSocket.WritableDataChannelStream._handleClosed (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\data-channels\writab
le-stream.js:154:3)
    at WebSocket._flush (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\data-channels\writable-stream.js:87:24)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at WebSocket.cleanupWebsocketResources (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\ws\lib\WebSocket.js:950:8
)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)

C:\Users\Dani Marion\Desktop>(
echo 19
 storj -k meije0612 upload-file 57b05629905cfece30b430f0 D:\films\*  1>>C:\StorjUpload.log
)
19
C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\async\lib\async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\async\lib\async.js:43:36
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:536:16
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:352:16
    at Request._callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:1005:14)
    at self.callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\request\request.js:187:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at null._onTimeout (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\request\request.js:762:12)
    at Timer.listOnTimeout (timers.js:92:15)

C:\Users\Dani Marion\Desktop>
```

**Comment by MeijeSibbel** [comment]
Also occurs with the latest core release v4.0.0:

```
 [Mon Oct 03 2016 19:53:50 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for dcef9703857f9adfb75f7ec9093c7cc68c7bceb5 (retry: 0)
 [Mon Oct 03 2016 19:53:59 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 4734e28ec51c72369cd4410ceeaf7c049a0d840a (retry: 2)
 [Mon Oct 03 2016 19:54:00 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for dcef9703857f9adfb75f7ec9093c7cc68c7bceb5 (retry: 1)
 [Mon Oct 03 2016 19:54:04 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 8 remaining...
C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\async\lib\async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\async\lib\async.js:43:36
    at BridgeClient._shardTransferComplete (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\storj-lib\lib\bridge-clie
nt\index.js:618:12)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\storj-lib\lib\bridge-cl
ient\index.js:682:11)
    at emitNone (events.js:72:20)
    at WritableDataChannelStream.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\storj-lib\node_modules\
flushwritable\lib\FlushWritable.js:32:33)
    at WebSocket.WritableDataChannelStream._handleClosed (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\storj-lib\l
ib\data-channels\writable-stream.js:154:3)
    at WebSocket._flush (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\storj-lib\lib\data-channels\writable-stream.
js:87:24)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at WebSocket.cleanupWebsocketResources (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\storj-lib\node_modules\ws
\lib\WebSocket.js:950:8)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)

Waiting for 0 seconds, press a key to continue ...
```

**Comment by lakewik** [comment]
Same error: 
`[Wed Oct 05 2016 20:22:54 GMT+0200 (CEST)] [info]   Contract negotiated with: {"protocol":"0.8.1","address":"209.6.52.154","port":16859,"nodeID":"cd424b85afe4d2788b1b8860d7883daba9703f32","lastSeen":1475691773718}
 [Wed Oct 05 2016 20:22:54 GMT+0200 (CEST)] [info]   Data channel opened, transferring shard...
 [Wed Oct 05 2016 20:22:56 GMT+0200 (CEST)] [warn]   Failed to transfer shard, reason: Unspecified error occurred
 [Wed Oct 05 2016 20:23:31 GMT+0200 (CEST)] [info]   Shard transfer completed! 2 remaining...
/home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/node_modules/async/lib/async.js:43:36
    at BridgeClient._shardTransferComplete (/home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/lib/bridge-client/index.js:611:3)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (/home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/lib/bridge-client/index.js:666:11)
    at emitNone (events.js:72:20)
    at WritableDataChannelStream.emit (events.js:166:7)
    at WritableDataChannelStream.<anonymous> (/home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/node_modules/flushwritable/lib/FlushWritable.js:32:33)
    at WebSocket.WritableDataChannelStream._handleClosed (/home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/lib/data-channels/writable-stream.js:154:3)
    at WebSocket._flush (/home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/lib/data-channels/writable-stream.js:87:24)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at WebSocket.cleanupWebsocketResources (/home/lakewik/.nvm/versions/node/v4.4.4/lib/node_modules/storj/node_modules/ws/lib/WebSocket.js:950:8)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
`
