### ISSUE TITLE
warning: possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by Puychack** [Storj/core#481]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storjshare-cli@7.0.0 /home/bigminer/storjshare-next/node_modules/storjshare-cli
└── storj-lib@4.0.0

```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Program shouldn't throw warning
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
When running, storjshare-cli frequently throws the following warning :

(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Sbucket.addListener (events.js:239:17)
    at Sbucket.once (events.js:265:8)
    at Sbucket.open (/home/bigminer/storjshare-next/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/s-bucket.js:110:30)
    at Btable._getSbucketForKey (/home/bigminer/storjshare-next/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/b-table.js:149:20)
    at _getStat (/home/bigminer/storjshare-next/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/b-table.js:195:10)
    at /home/bigminer/storjshare-next/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:1069:13
    at replenish (/home/bigminer/storjshare-next/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:884:21)
    at iterateeCallback (/home/bigminer/storjshare-next/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:869:21)
    at /home/bigminer/storjshare-next/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:847:20
    at /home/bigminer/storjshare-next/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/node_modules/async/dist/async.js:1071:17
    at /home/bigminer/storjshare-next/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/b-table.js:205:9
    at /home/bigminer/storjshare-next/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kfs/lib/s-bucket.js:373:7

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Just run storjshare-cli and wait

**Comment by lunokhod** [comment]
I get this error when installing storjshare-cli on OSX
```
% npm install -g storjshare-cli
(node:93842) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:93842) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:93842) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:93842) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:93842) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:93842) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:93842) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:93842) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:93842) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:93842) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:93842) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:93842) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:93842) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/storjshare -> /usr/local/lib/node_modules/storjshare-cli/bin/storjshare.js
/usr/local/lib
└─┬ storjshare-cli@7.0.1 
  └─┬ storj-lib@4.0.2
    └── ntp-client@0.5.4  (git://github.com/bookchin/node-ntp-client.git#4eb7ffa659596d9ea23a3fdc10f3355112efb811)
```
