### ISSUE TITLE
if (fn === null) throw new Error("Callback was already called.");

### ISSUE THREAD

**Issue by yuilleb** [Storj/core#493]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
/usr/local/lib
âââ storj@3.2.3
```

Replace the values below using the output from `node --version`.

```
v6.6.0
```

### Actual Behavior

```
{"level":"warn","message":"Timeout waiting for NTP response.","timestamp":"2016-10-11T07:09:43.943Z"}
{"level":"info","message":"resolving seeds from https://api.storj.io","timestamp":"2016-10-11T07:09:43.945Z"}
{"level":"debug","message":"Request: {\"baseUrl\":\"https://api.storj.io\",\"uri\":\"/contacts\",\"method\":\"GET\",\"timeout\":20000,\"qs\":{\"connected\":true,\"__nonce\":\"efdccfc6-474b-432c-8c5d-4814ecec1517\"},\"json\":true}","timestamp":"2016-10-11T07:09:43.946Z"}
{"level":"debug","message":"checking pending rpc callbacks for expirations","timestamp":"2016-10-11T07:09:48.921Z"}
{"level":"warn","message":"getaddrinfo EAI_AGAIN","timestamp":"2016-10-11T07:09:53.935Z"}
/usr/local/lib/node_modules/storjshare-cli/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/async/lib/async.js:43:36
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/async/lib/async.js:723:17
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/async/lib/async.js:167:37
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:905:5
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/utils.js:272:14
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/utils.js:252:16
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/ntp-client/lib/ntp-client.js:78:17
    at doSend (dgram.js:374:7)
    at afterDns (dgram.js:366:5)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:17)

```

### Steps to Reproduce

I started up storjshare at a time where my internet happened to be down. My initial guess is that's how it can be reproduced, but I have no easy way to test this at the moment.

**Comment by bookchin** [comment]
I need to pull https://github.com/moonpyk/node-ntp-client/pull/6 into my fork

**Comment by bookchin** [comment]
Done. https://github.com/bookchin/node-ntp-client/commit/9edb9e3c44aa5ccd963e19cd709191a2dc07e2ea

Re-installing deps should fix this issue.
