### ISSUE TITLE
Connection Termination Not Handled

### ISSUE THREAD

**Issue by super3** [Storj/core#496]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
 -> C:\Users\work\AppData\Roaming\nvm\v4.5.0 C:\Program Files\nodejs
└── storj@3.2.3
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

Download to success.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
 [Tue Oct 11 2016 13:37:14 GMT-0400 (Eastern Daylight Time)] [info]   Received 107872256 of 10737418240 bytes
 [Tue Oct 11 2016 13:37:14 GMT-0400 (Eastern Daylight Time)] [info]   Received 108003328 of 10737418240 bytes
 [Tue Oct 11 2016 13:37:14 GMT-0400 (Eastern Daylight Time)] [info]   Received 108134400 of 10737418240 bytes
 [Tue Oct 11 2016 13:37:15 GMT-0400 (Eastern Daylight Time)] [info]   Received 108265472 of 10737418240 bytes
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error
    at WebSocket.<anonymous> (C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\lib\data-channels\readable-stream.js:30:26)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at WebSocket.cleanupWebsocketResources (C:\Users\work\AppData\Roaming\nvm\v4.5.0\node_modules\storj\node_modules\ws\lib\WebSocket.js:950:8)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload a 10 GB file.
2. Download will break at some point.

**Comment by super3** [comment]
```$ storj download-file 57fd1cba26adcf743a1adc2c 57fd1fb526adcf743a1ae809 C:\Users\work\Desktop\dump10
 [Tue Oct 11 2016 14:52:13 GMT-0400 (Eastern Daylight Time)] [info]   Name: dump10, Type: application/octet-stream, Size: 11274289152 bytes, ID: 57fd1fb526adcf743a1ae809
 [...]  > Enter your passphrase to unlock your keyring  >   [Tue Oct 11 2016 14:52:13 GMT-0400 (Eastern Daylight Time)] [error]  file 57fd1fb526adcf743a1ae809 does not exist in bucket 57fd1cba26adcf743a1adc2c
******

 [Tue Oct 11 2016 14:52:15 GMT-0400 (Eastern Daylight Time)] [info]   Creating retrieval token...
 [Tue Oct 11 2016 14:52:16 GMT-0400 (Eastern Daylight Time)] [info]   Resolving 6 file pointers...
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Creating retrieval token...
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 262144 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 393216 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 655360 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 917504 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 1179648 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 1441792 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 1703936 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 1966080 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 2228224 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 2490368 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 2752512 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 2883584 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 3145728 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 3407872 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 3670016 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 3932160 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Resolving 6 file pointers...
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 4194304 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 4325376 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 4587520 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 4849664 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 5111808 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 5373952 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 5505024 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 5767168 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 6029312 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 6160384 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 6422528 of 3221225472 bytes
 [Tue Oct 11 2016 14:52:17 GMT-0400 (Eastern Daylight Time)] [info]   Received 6553600 of 3221225472 bytes```
