### ISSUE TITLE
TypeError: item.shard.destroy is not a function

### ISSUE THREAD

**Issue by yuilleb** [Storj/core#497]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
/usr/local/lib
âââ storj@3.2.3
```

Replace the values below using the output from `node --version`.

```
v6.6.0
```

### Expected Behavior

After running into an invalid shard hash, should delete shard and continue on.

### Actual Behavior

Crashes when trying to delete a shard with an invalid hash.

```
{"level":"warn","message":"calculated hash does not match the expected result","timestamp":"2016-10-12T13:34:57.611Z"}
/usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/data-channels/server.js:260
        item.shard.destroy();
                   ^

TypeError: item.shard.destroy is not a function
    at PassThrough.<anonymous> (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/data-channels/server.js:260:20)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (/usr/local/lib/node_modules/storjshare-cli/node_modules/readable-stream/lib/_stream_readable.js:922:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Steps to Reproduce

Looks like a shard has to have an incorrect hash to trigger this.

**Comment by bookchin** [comment]
Looks like you are running an old version of `storj` and an unsupported version of node (we support the LTS release 4.x.x). Try installing the latest.

**Comment by yuilleb** [comment]
@bookchin Sorry, didn't pay attention to the commands I was outputting at top. This bug triggers in storjshare which is running 4.0.2.

```
$ storjshare --version
StorjShare: 7.0.1
Core:       4.0.2
Protocol:   0.9.0
```

Did you implement a `shard.destroy()` function? When searching the repository all I can find are stubs during unit tests.

**Comment by bookchin** [comment]
Yes:

* https://github.com/Storj/kfs/blob/master/lib/read-stream.js#L77
* https://github.com/Storj/kfs/blob/master/lib/write-stream.js#L63

But, there must be something else wrong.

**Comment by yuilleb** [comment]
OK, obviously it occurred with the WritableFileStream as I was accepting an uploaded shard. I wonder if in fact item.shard was a valid WritableFileStream at the time of attempting to call `destroy()`?

**Comment by yuilleb** [comment]
Here's some more logs before the typeerror occurred:

```
{"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-10-12T13:34:56.815Z"}
{"level":"debug","message":"received contract offer...","timestamp":"2016-10-12T13:34:56.840Z"}
{"level":"debug","message":"pending offers 0 is less than concurrency true: 4","timestamp":"2016-10-12T13:34:56.840Z"}
{"level":"info","message":"sending PUBLISH message to {\"userAgent\":\"4.0.2\",\"protocol\":\"0.9.0\",\"address\":\"37.97.185.28\",\"port\":4100,\"nodeID\":\"0f77a4ce2c34ff7d3e121bc5ac065a12589a9f3a\",\"lastSeen\":1476279296841}","timestamp":"2016-10-12T13:34:56.841Z"}
{"level":"debug","message":"queuing callback for reponse to bce6c9cf0400e3d8780daac2243b274fcea775ca","timestamp":"2016-10-12T13:34:56.852Z"}
{"level":"debug","message":"no storage item available for this shard","timestamp":"2016-10-12T13:34:56.853Z"}
{"level":"debug","message":"negotiator returned: true","timestamp":"2016-10-12T13:34:56.853Z"}
{"level":"debug","message":"we have enough free space: true","timestamp":"2016-10-12T13:34:56.853Z"}
{"level":"debug","message":"Sending offer for contract","timestamp":"2016-10-12T13:34:56.950Z"}
{"level":"info","message":"sending OFFER message to {\"userAgent\":\"4.0.1\",\"protocol\":\"0.9.0\",\"address\":\"104.196.0.239\",\"port\":8453,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1476279296950}","timestamp":"2016-10-12T13:34:56.950Z"}
{"level":"debug","message":"queuing callback for reponse to 716475661c6719a44f14024b47276c20eb971715","timestamp":"2016-10-12T13:34:56.971Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"4.0.1\",\"protocol\":\"0.9.0\",\"address\":\"104.196.0.239\",\"port\":8453,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1476279297090}","timestamp":"2016-10-12T13:34:57.090Z"}
{"level":"debug","message":"updating contact {\"userAgent\":\"4.0.1\",\"protocol\":\"0.9.0\",\"address\":\"104.196.0.239\",\"port\":8453,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1476279297090}","timestamp":"2016-10-12T13:34:57.090Z"}
{"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-10-12T13:34:57.090Z"}
{"level":"debug","message":"checking pending rpc callback stack for 716475661c6719a44f14024b47276c20eb971715","timestamp":"2016-10-12T13:34:57.120Z"}
{"level":"warn","message":"Offers for this contract are now locked","timestamp":"2016-10-12T13:34:57.121Z"}
{"level":"warn","message":"calculated hash does not match the expected result","timestamp":"2016-10-12T13:34:57.611Z"}
/usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/data-channels/server.js:260
        item.shard.destroy();
                   ^

TypeError: item.shard.destroy is not a function
    at PassThrough.<anonymous> (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/data-channels/server.js:260:20)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (/usr/local/lib/node_modules/storjshare-cli/node_modules/readable-stream/lib/_stream_readable.js:922:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by bookchin** [comment]
Looks like this is a bug where we are actually returning a transform stream wrapper around the writable stream that doesn't include the `destroy()` method. https://github.com/Storj/kfs/blob/master/lib/s-bucket.js#L353

**Comment by yuilleb** [comment]
wow nice find @bookchin! you are on a roll today smashing bugs
