### ISSUE TITLE
TypeError: Data must be a string or a buffer

### ISSUE THREAD

**Issue by lunokhod** [Storj/core#508]
```
% storjshare -V
StorjShare: 7.0.1
Core:       4.0.2
Protocol:   0.9.0
```

I have been getting the following error sporadically with the latest version:

```
storjshare-backup-1 {"level":"info","message":"sending PUBLISH message to {\"userAgent\":\"4.0.2\",\"protocol\":\"0.9.0\",\"address\":\"server2dk.ddns.net\",\"port\":4000,\"nodeID\":\"8533c647bb9825f5585fc9685b8b4bba23fe90e4\",\"lastSeen\":1476384083416}","timestamp":"2016-10-13T18:41:23.416Z"}
storjshare-backup-1 TypeError: Data must be a string or a buffer
storjshare-backup-1     at TypeError (native)
storjshare-backup-1     at Hash.update (crypto.js:74:16)
storjshare-backup-1     at Object.module.exports.hashKey (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/utils.js:45:44)
storjshare-backup-1     at Object.module.exports.coerceKeyOrIndex (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/utils.js:60:28)
storjshare-backup-1     at _getStat (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/b-table.js:193:21)
storjshare-backup-1     at /usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1069:13
storjshare-backup-1     at replenish (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:884:21)
storjshare-backup-1     at /usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:888:13
storjshare-backup-1     at _asyncMap (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1067:9)
storjshare-backup-1     at Object.mapLimit (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1151:20)
storjshare-backup-1     at Btable.stat (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/b-table.js:213:9)
storjshare-backup-1     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/storage/adapters/embedded.js:173:16
```

**Comment by bookchin** [comment]
Already fixed in master. Release shortly

**Comment by bookchin** [comment]
https://github.com/Storj/core/commit/2e2aa559f89e972880e416b184bccb6952723549

**Comment by lunokhod** [comment]
I'm still getting this error in 4.0.4
```
storjshare -V
StorjShare: 7.0.1
Core:       4.0.4
Protocol:   0.9.0
```

```
storjshare-backup-1 {"level":"info","message":"sending PUBLISH message to {\"userAgent\":\"4.0.4\",\"protocol\":\"0.9.0\",\"address\":\"symbiont.spdns.de\",\"port\":6070,\"nodeID\":\"60c175f4d1e140bcb3eeb1b909080eb80321c5c1\",\"lastSeen\":1476479208692}","timestamp":"2016-10-14T21:06:48.692Z"}
storjshare-backup-1 TypeError: Data must be a string or a buffer
storjshare-backup-1     at TypeError (native)
storjshare-backup-1     at Hash.update (crypto.js:74:16)
storjshare-backup-1     at Object.module.exports.hashKey (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/utils.js:45:44)
storjshare-backup-1     at Object.module.exports.coerceKeyOrIndex (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/utils.js:60:28)
storjshare-backup-1     at _getStat (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/b-table.js:193:21)
storjshare-backup-1     at /usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1144:13
storjshare-backup-1     at replenish (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1018:21)
storjshare-backup-1     at /usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1022:13
storjshare-backup-1     at _asyncMap (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1142:9)
storjshare-backup-1     at Object.mapLimit (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/node_modules/async/dist/async.js:1228:20)
storjshare-backup-1     at Btable.stat (/usr/local/lib/node_modules/storjshare-cli/node_modules/kfs/lib/b-table.js:213:9)
storjshare-backup-1     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/storage/adapters/embedded.js:173:16
````

**Comment by littleskunk** [comment]
Fixed in core 4.0.6.

**Comment by lunokhod** [comment]
problem persists in 4.0.6
```
% storjshare -V
StorjShare: 7.0.1
Core:       4.0.6
Protocol:   0.9.1
```

**Comment by lunokhod** [comment]
same problem with core 4.1.
```
storjshare -V
StorjShare: 7.0.3
Core:       4.1.0
Protocol:   0.9.1
```

**Comment by bookchin** [comment]
@lunokhod this is an issue in KFS. i think i've tracked it down, but need some info. can you `ls` your `sharddata.kfs` directory for me pl0x?

**Comment by bookchin** [comment]
Duplicate https://github.com/Storj/kfs/issues/36
