### ISSUE TITLE
return binding.rmdir(pathModule._makeLong(path));

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#524]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@1.0.3 /home/gordon/Code/storj-bridge
└── storj@4.0.6  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.6.0
```
### Command

```
set temp=E:\Upload\temp

for /l %%x in (1, 1, 1000) do (
   echo %%x
   storj -k meije0612 -r 12 upload-file 57af3a1e8f266a7d4e391055 D:\films\*   
   TIMEOUT 2
)
```

### Expected Behavior

Upload continues without a problem.

### Actual Behavior

```
 [Mon Oct 17 2016 23:16:49 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 3c3397a5d70cc75ba65be44e1ab8c357a85a9122 (retry: 20)
 [Mon Oct 17 2016 23:16:49 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for ea7706d505951b188c3099f5fc622b77b021a7ae (retry: 23)
 [Mon Oct 17 2016 23:16:49 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 197855865b9f4d48c8d83154d8ca590be7fed20d (retry: 19)
 [Mon Oct 17 2016 23:16:50 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 03df82e044f994ce070c0b43a28dd1b2a8a77e98 (retry: 18)
 [Mon Oct 17 2016 23:16:50 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 587f10289bf9689a7e0d7b43ce31ea8a7cb4e0e9 (retry: 22)
 [Mon Oct 17 2016 23:16:50 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
 [Mon Oct 17 2016 23:16:50 GMT+0200 (W. Europe Daylight Time)] [warn]   [ A.Promise.2013.720p.BluRay.x264.YIFY.mp4 ] Error occurred. Triggering cleanup...
 [Mon Oct 17 2016 23:16:50 GMT+0200 (W. Europe Daylight Time)] [info]   [ A.Promise.2013.720p.BluRay.x264.YIFY.mp4 ] Cleaning up...
fs.js:758
  return binding.rmdir(pathModule._makeLong(path));
                 ^

Error: ENOTEMPTY: directory not empty, rmdir 'E:\Upload\temp\storj-42643fyg19oAh6BR'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at _rmdirRecursiveSync (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:285:10)
    at _cleanupCallback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\tmp\lib\tmp.js:409:5)
    at Uploader._cleanup (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:125:3)
    at Uploader._handleFailure (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:358:10)
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:405:10
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\async\lib\async.js:52:16
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\node_modules\async\lib\async.js:1209:30
    at UploadState.callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\uploader.js:284:9)
    at _handleError (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:513:18)
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:547:16
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:359:16
    at Request._callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:1016:14)
    at self.callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\node_modules\request\request.js:187:22)
    at emitOne (events.js:77:13)

Waiting for 0 seconds, press a key to continue ...

```

### Steps to Reproduce

Upload a file.

**Comment by bookchin** [comment]
This belongs in https://github.com/Storj/core-cli
