### ISSUE TITLE
RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core#546]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@2.0.0 /home/gordon/Code/storj-bridge
└── storj@5.0.0  -> /home/gordon/Code/storj-core
core-CLI: 2.0.0
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
No errors.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
C:\Users\Dani Marion\Desktop>(
echo 4
 storj -k meije0612 -r 12 upload-file 4c1dcb7b5b4b127936142f2d D:\movies\*  1>>D:\instance2.log
 TIMEOUT 2
)
4
buffer.js:11
    super(arg1, arg2, arg3);
    ^

RangeError: Array buffer allocation failed
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:11:5)
    at createUnsafeBuffer (buffer.js:38:12)
    at allocate (buffer.js:181:12)
    at Function.Buffer.allocUnsafe (buffer.js:141:10)
    at allocNewPool (fs.js:1864:17)
    at ReadStream._read (fs.js:1964:5)
    at ReadStream.Readable.read (_stream_readable.js:348:10)
    at readableAddChunk (_stream_readable.js:177:18)
    at ReadStream.Readable.push (_stream_readable.js:134:10)
    at onread (fs.js:2004:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:681:17)

Waiting for 0 seconds, press a key to continue ...
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run a upload script (1-2GB files).
2. ...
3. ...

**Comment by bookchin** [comment]
Looks like you do not have enough memory to perform the large of an upload.

**Comment by MeijeSibbel** [comment]
I do indeed get a few 'not enough memory' errors every once in a while.
