### ISSUE TITLE
TypeError: Property 1507

### ISSUE THREAD

**Issue by CJClaude** [Storj/core#580]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
StorjShare: 9.0.0
Core:       6.0.1
Protocol:   1.0.0
```

Replace the values below using the output from `node --version`.

```
V6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Farmer node runs without errors.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
tarting seeing these errors today, repeatedly:

/usr/lib64/node_modules/storjshare-cli/node_modules/knuth-shuffle/index.js:21
      array[currentIndex] = array[randomIndex];
                          ^

TypeError: Cannot assign to read only property '1507' of string '[{"address":"pspoe.carpenter-farms.us","lastSeen":"2016-12-05T21:32:55.736Z","port":4770,"protocol":"1.0.0","nodeID":"e79616f50c63960b7dc0e938adc72e01e49d29fc"},{"address":"78.10.231.191","lastSeen":"2016-12-05T21:32:55.736Z","port":4080,"protocol":"1.0.0","nodeID":"82d291983ce476771f2d6f190b108aed1138a940"},{"address":"server011.storj.dk","lastSeen":"2016-12-05T21:32:55.736Z","port":5011,"protocol":"1.0.0","nodeID":"0698546f86ae720e3393f1e900c44a1b64678c9a"},{"address":"78.10.231.191","lastSeen":"2016-12-05T21:32:55.736Z","port":4040,"protocol":"1.0.0","nodeID":"ef9c0557113748600205262884d435ee29d0e4f4"},{"address":"78.10.231.191","lastSeen":"2016-12-05T21:32:55.736Z","port":4030,"protocol":"1.0.0","nodeID":"58ba5cc2b78508f66014cd42385a0891847945cc"},{"address":"78.10.231.191","lastSeen":"2016-12-05T21:32:55.736Z","port":4060,"protocol":"1.0.0","nodeID":"3e320cac40a953bd38774e69357594269153a213"},{"address":"78.10.231.191","lastSeen":"2016-12-05T21:32:55.736Z","port":4070,"protocol":"1.0.0","nodeID":"99c2b4c3b8573adc7a1f82150353dbf8f8dddefd"},{"address":"78.10.231.191","lastSeen":"2016-12-05T21:32:55.736Z","port":4000,"protocol":"1.0.0","nodeID":"71bd38b07a46c168fa3cbdc20e09b3c8460bc3fc"},{"address":"78.10.231.191","lastSeen":"2016-12-05T21:32:55.736Z","port":4010,"protocol":"1.0.0","nodeID":"55cc9b9b4289e91226182ad7722a9cbf84a759cd"},{"address":"78.10.231.191","lastSeen":"2016-12-05T21:32:55.736Z","port":4050,"protocol":"1.0.0","nodeID":"56d2c4dc40b9bb44dcb48f2b2d59d556f7b6a7c4"},]'
    at shuffle (/usr/lib64/node_modules/storjshare-cli/node_modules/knuth-shuffle/index.js:21:27)
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:303:30
    at Request._callback (/usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/lib/bridge-client/index.js:1101:5)
    at Request.self.callback (/usr/lib64/node_modules/storjshare-cli/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib64/node_modules/storjshare-cli/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib64/node_modules/storjshare-cli/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Steps to Reproduce
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Running against seed002.storj.dk
2. ...
3. ...

**Comment by bookchin** [comment]
Looks like the problem here is the the DK seed pool sends back improperly formatted JSON (look at the trailing comma) which causes the response to be processed as a string, which is then shuffled as if it is an array of contact objects where it fails with the type error. @th3van would need to fix this on his side.

**Comment by Th3Van** [comment]
Fixed on both pools now.

//Th3Van
