### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by yuilleb** [Storj/core#595]
### Package Versions
```
StorjShare: 9.0.5
Core:       6.0.8
Protocol:   1.0.0
```

Replace the values below using the output from `node --version`.

```
v6.6.0
```

### Expected Behavior

Should handle exception.

### Actual Behavior

```
{"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-12-13T08:20:34.609Z"}
{"level":"info","message":"replying to message to fa2a829d9a9fa221a0ce75c200191c8a86a63cb1","timestamp":"2016-12-13T08:20:34.610Z"}
{"level":"debug","message":"not waiting on callback for message fa2a829d9a9fa221a0ce75c200191c8a86a63cb1","timestamp":"2016-12-13T08:20:34.636Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.0.7\",\"protocol\":\"1.0.0\",\"address\":\"91.244.113.103\",\"port\":852,\"nodeID\":\"47ba4573af6dd012c68bc55969e72b085aa0e288\",\"lastSeen\":1481617234802}","timestamp":"2016-12-13T08:20:34.803Z"}
{"level":"debug","message":"updating contact {\"userAgent\":\"6.0.7\",\"protocol\":\"1.0.0\",\"address\":\"91.244.113.103\",\"port\":852,\"nodeID\":\"47ba4573af6dd012c68bc55969e72b085aa0e288\",\"lastSeen\":1481617234802}","timestamp":"2016-12-13T08:20:34.803Z"}
{"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-12-13T08:20:34.803Z"}
{"level":"debug","message":"checking pending rpc callback stack for d4a455d535e89b91b47bb968b48bc0bfa5faf924","timestamp":"2016-12-13T08:20:34.803Z"}
{"level":"info","message":"replying to message to 1383f2d8befee9ec80e629614d286fc7bb9900c0","timestamp":"2016-12-13T08:20:34.803Z"}
{"level":"debug","message":"not waiting on callback for message 1383f2d8befee9ec80e629614d286fc7bb9900c0","timestamp":"2016-12-13T08:20:34.832Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.0.8\",\"protocol\":\"1.0.0\",\"address\":\"174.storj.eu\",\"port\":7400,\"nodeID\":\"47c9703763008b693a99c32468339f3c72f7dbf1\",\"lastSeen\":1481617234833}","timestamp":"2016-12-13T08:20:34.833Z"}
{"level":"debug","message":"updating contact {\"userAgent\":\"6.0.8\",\"protocol\":\"1.0.0\",\"address\":\"174.storj.eu\",\"port\":7400,\"nodeID\":\"47c9703763008b693a99c32468339f3c72f7dbf1\",\"lastSeen\":1481617234833}","timestamp":"2016-12-13T08:20:34.833Z"}
{"level":"debug","message":"contact not in bucket, moving to head","timestamp":"2016-12-13T08:20:34.833Z"}
{"level":"debug","message":"checking pending rpc callback stack for 2fe2cba84d47932c67415faa7c51306610195770","timestamp":"2016-12-13T08:20:34.835Z"}
{"level":"info","message":"replying to message to 63d8013752bc8bcb18c7bd25d18938d0d1a697ca","timestamp":"2016-12-13T08:20:34.835Z"}
{"level":"debug","message":"not waiting on callback for message 63d8013752bc8bcb18c7bd25d18938d0d1a697ca","timestamp":"2016-12-13T08:20:34.866Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.0.8\",\"protocol\":\"1.0.0\",\"address\":\"174.storj.eu\",\"port\":7400,\"nodeID\":\"47c9703763008b693a99c32468339f3c72f7dbf1\",\"lastSeen\":1481617235098}","timestamp":"2016-12-13T08:20:35.098Z"}
{"level":"debug","message":"updating contact {\"userAgent\":\"6.0.8\",\"protocol\":\"1.0.0\",\"address\":\"174.storj.eu\",\"port\":7400,\"nodeID\":\"47c9703763008b693a99c32468339f3c72f7dbf1\",\"lastSeen\":1481617235098}","timestamp":"2016-12-13T08:20:35.098Z"}
{"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-12-13T08:20:35.098Z"}
{"level":"debug","message":"checking pending rpc callback stack for babd9c173522e2e8a191033759b1eb972a15d78e","timestamp":"2016-12-13T08:20:35.099Z"}
{"level":"info","message":"replying to message to 3fc947e27fc100cc2a4fbabba62aa15f86354f83","timestamp":"2016-12-13T08:20:35.099Z"}
{"level":"debug","message":"not waiting on callback for message 3fc947e27fc100cc2a4fbabba62aa15f86354f83","timestamp":"2016-12-13T08:20:35.122Z"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 104.196.196.231:8450
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
```

### Steps to Reproduce

1. Run storjshare for a while

**Comment by bookchin** [comment]
Node v6.6.0 is not supported. Upgrade to LTS (6.9.x) and please let me know if this is reproducible with the [storjshare-daemon](https://github.com/storj/storjshare-daemon) package (storjshare-cli is deprecated).

**Comment by yuilleb** [comment]
Same. Not seen this with storjshare-daemon

**Comment by bookchin** [comment]
👍 👍 👍
