### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by yuilleb** [Storj/core#596]
### Package Versions

```
StorjShare: 9.0.5
Core:       6.0.8
Protocol:   1.0.0
```

```
v6.6.0
```

### Expected Behavior

Handles the exception

### Actual Behavior

```
{"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-12-13T22:05:28.750Z"}
{"level":"debug","message":"checking pending rpc callback stack for b38b8f46340052d0037812df9c7b8314763d1e1e","timestamp":"2016-12-13T22:05:28.751Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.0.8\",\"protocol\":\"1.0.0\",\"address\":\"64.137.167.127\",\"port\":4000,\"nodeID\":\"41532f0bb120b519e7b809ed4cfdc0c821fd1067\",\"lastSeen\":1481666728764}","timestamp":"2016-12-13T22:05:28.764Z"}
{"level":"debug","message":"updating contact {\"userAgent\":\"6.0.8\",\"protocol\":\"1.0.0\",\"address\":\"64.137.167.127\",\"port\":4000,\"nodeID\":\"41532f0bb120b519e7b809ed4cfdc0c821fd1067\",\"lastSeen\":1481666728764}","timestamp":"2016-12-13T22:05:28.764Z"}
{"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-12-13T22:05:28.764Z"}
{"level":"debug","message":"checking pending rpc callback stack for 3a3160d2becae96e1b24bcab76648f6855aba4be","timestamp":"2016-12-13T22:05:28.765Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.0.5\",\"protocol\":\"1.0.0\",\"address\":\"52.174.42.227\",\"port\":5000,\"nodeID\":\"4649821c9800ab78b18051c91e26ec236269f443\",\"lastSeen\":1481666728836}","timestamp":"2016-12-13T22:05:28.836Z"}
{"level":"debug","message":"updating contact {\"userAgent\":\"6.0.5\",\"protocol\":\"1.0.0\",\"address\":\"52.174.42.227\",\"port\":5000,\"nodeID\":\"4649821c9800ab78b18051c91e26ec236269f443\",\"lastSeen\":1481666728836}","timestamp":"2016-12-13T22:05:28.836Z"}
{"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-12-13T22:05:28.836Z"}
{"level":"debug","message":"checking pending rpc callback stack for c0979214984806313451de3bd6abefe10355ded2","timestamp":"2016-12-13T22:05:28.837Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.0.8\",\"protocol\":\"1.0.0\",\"address\":\"STORJ-CLUS-130.storj.space\",\"port\":4000,\"nodeID\":\"441d4e0e1b9f0080ecadee7fe182acd32361a6cf\",\"lastSeen\":1481666728920}","timestamp":"2016-12-13T22:05:28.920Z"}
{"level":"debug","message":"updating contact {\"userAgent\":\"6.0.8\",\"protocol\":\"1.0.0\",\"address\":\"STORJ-CLUS-130.storj.space\",\"port\":4000,\"nodeID\":\"441d4e0e1b9f0080ecadee7fe182acd32361a6cf\",\"lastSeen\":1481666728920}","timestamp":"2016-12-13T22:05:28.920Z"}
{"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2016-12-13T22:05:28.920Z"}
{"level":"debug","message":"received contract offer...","timestamp":"2016-12-13T22:05:28.921Z"}
{"level":"debug","message":"pending offers 0 is less than concurrency true: 1","timestamp":"2016-12-13T22:05:28.922Z"}
{"level":"warn","message":"too many active transfers 4, not sending offer","timestamp":"2016-12-13T22:05:28.922Z"}
{"level":"debug","message":"negotiator returned: false","timestamp":"2016-12-13T22:05:28.922Z"}
{"level":"debug","message":"we have enough free space: true","timestamp":"2016-12-13T22:05:28.922Z"}
{"level":"info","message":"replying to message to 16da90939755f04b7917e02ad57cd493877ff1f1","timestamp":"2016-12-13T22:05:28.922Z"}
{"level":"debug","message":"not waiting on callback for message 16da90939755f04b7917e02ad57cd493877ff1f1","timestamp":"2016-12-13T22:05:28.937Z"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

### Steps to Reproduce

1. Run for a while

**Comment by bookchin** [comment]
Node v6.6.0 is not supported. Upgrade to LTS (6.9.x) and please let me know if this is reproducible with the [storjshare-daemon](https://github.com/storj/storjshare-daemon) package (storjshare-cli is deprecated).

**Comment by yuilleb** [comment]
I've not run into this with storjshare-daemon

**Comment by bookchin** [comment]
Good deal. Closing then. 👍
