### ISSUE TITLE
Tunnel server crash

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#676]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
daemon: 2.5.0,
core: 6.3.0,
protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.10.0
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

Farmer is connected via port forwarding and public ip. Offering additional 3 tunnel connection to other farmer. I would expect that these tunnel connection are stable and the tunnel server doesn't crash.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
{"level":"info","message":"opening gateway for 9d412b18e66eaab5901d0a877e02aa85472e6455","timestamp":"2017-02-27T17:23:29.904Z"}
{"level":"info","message":"opening gateway for a267075dc79d03e541bb3eecee15042b77421c7b","timestamp":"2017-02-28T01:52:40.812Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-02-28T01:56:24.307Z"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)

{"level":"info","message":"opening gateway for 0230cefb5a0469bc1aec136efb476524156e8dd6","timestamp":"2017-02-28T14:40:10.783Z"}
{"level":"info","message":"opening gateway for 7d14ce7520eb584638c4d78e4be22dfe8d495788","timestamp":"2017-03-04T17:52:12.484Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-04T17:57:19.919Z"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)

{"level":"info","message":"opening gateway for 9e3b4f380c682a5e5cbfa88ef939c9d6ad93fd9e","timestamp":"2017-03-06T06:22:57.118Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:30.103Z"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start farming with and offer the 3 default tunnel connection
2. Keep it running for a few days and wait for a tunnel connection

Maybe start 3 other farmer and use the main farmer as seed and ask him for a tunnel connection. I didn't try it but that should reproduce the issue in a few minutes.

**Comment by littleskunk** [comment]
5942 {"level":"info","message":"tunneling request through to client","timestamp":"2017-02-23T14:24:56.645Z"}
5513 {"level":"info","message":"forwarding tunneled response back to requester","timestamp":"2017-02-23T14:24:57.309Z"}
5945 {"level":"info","message":"response finished, destroying connection","timestamp":"2017-02-23T14:24:57.309Z"}

**Comment by ne0ark** [comment]
Hello,

I am seeing this also:

```
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-25T19:14:50.265Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-25T19:14:50.307Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-25T19:14:50.329Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-25T19:14:50.331Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-25T19:14:50.388Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-25T19:14:50.429Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-25T19:14:50.453Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-25T19:14:50.539Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-25T19:14:50.541Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-25T19:14:50.578Z"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:572:26)
{"level":"warn","message":"your address is public and traversal strategies are disabled","timestamp":"2017-03-25T19:14:52.655Z"}
{"level":"info","message":"node created with nodeID 42d1125aef7df4ce2e4777550afbeee01aee3877","timestamp":"2017-03-25T19:14:52.666Z"}
{"level":"info","message":"clock is synchronized with ntp, delta: -8 ms","timestamp":"2017-03-25T19:14:52.982Z"}
{"level":"info","message":"resolving seeds from https://api.storj.io","timestamp":"2017-03-25T19:14:52.985Z"}
{"level":"info","message":"attempting to join network via storj://client023.storj.dk:15068/69bd62ca4e2853eecd5ffbe6cf5c847f76737c55","timestamp":"2017-03-25T19:14:53.427Z"}
{"level":"info","message":"sending FIND_NODE message to {\"userAgent\":\"6.3.2\",\"protocol\":\"1.1.0\",\"address\":\"client023.storj.dk\",\"port\":15068,\"nodeID\":\"69bd62ca4e2853eecd5ffbe6cf5c847f76737c55\",\"lastSeen\":1490469293429}","timestamp":"2017-03-25T19:14:53.433Z"}
```

**Comment by bookchin** [comment]
Let's track this at https://github.com/bookchin/diglet

**Comment by littleskunk** [comment]
https://github.com/bookchin/diglet/issues/2
