### ISSUE TITLE
Farmer crashes after daemon 4.0.0/4.0.1 upgrade (which includes v7.0.0 of core)

### ISSUE THREAD

**Issue by felixbrucker** [Storj/core#720]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storjshare-daemon: 4.0.1
core: 7.0.0
```

Replace the values below using the output from `node --version`.

```
v6.11.2
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

The farmer doesn't crash.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

The farmer crashes (randomly), but only one node seems to be affected. Other nodes are in different geolocations.

```
/home/felix/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/farmer.js:447
  const sigObj = secp256k1.sign(sighash, privkey);
                           ^

RangeError: private key length is invalid
    at RangeError (native)
    at FarmerInterface.bridgeRequest (/home/felix/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/farmer.js:447:28)
    at ShardServer._sendExchangeReport (/home/felix/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/shard-server.js:150:24)
    at ReadableFileStream._handleTransferFinish (/home/felix/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/shard-server.js:312:12)
    at emitNone (events.js:91:20)
    at ReadableFileStream.emit (events.js:185:7)
    at endReadableNT (/home/felix/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/readable-stream/lib/_stream_readable.js:992:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

I have not yet found a way to reproduce the problem.

**Comment by him2him2** [comment]
I was also having this problem after upgrading. I have 6 nodes on that box but only one was having this problem. It was so bad that the node stopped after 30 restart re-trys.

I seem to have been able to resolve this problem by stopping all nodes:

> storjshare-killall

Then re-trying the upgrade:

> npm install --global storjshare-daemon

Then restarting all the nodes.

All nodes have been running with no issues for 10 mins. Will keep an eye on it.

**Comment by aleitner** [comment]
If you can get it, what's the length of your private keys? Have a feeling if it starts with two 0s then it chops off the first one

**Comment by braydonf** [comment]
Found the issue, will have PR for it shortly.

**Comment by felixbrucker** [comment]
i have taken a look at the private key in question, it does not start with any zeros:

`f263cd7a83f455ab5fb54fe74e81f1c50f7f83fc45dedd23f00b860a37f5f3`

i have changed one character in the middle, but i really do not care if somebody where to find the real key, i do not use it anymore.

i have not yet tried running that share yet again

**Comment by braydonf** [comment]
Yep, there are two leading zeros for that, the length is 62, when it should be 64. It's how the big number for the key is made into a string. The logic for why it's not padded is because we don't usually write 000010 and 000011, however with private keys the length is supposed to always be the same.
