### ISSUE TITLE
TypeError: Cannot read property 'warn' of undefined

### ISSUE THREAD

**Issue by AlexeyALeonov** [Storj/core#727]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
C:\Users\USER\AppData\Roaming\npm
`-- storjshare-daemon@4.0.1
```

Replace the values below using the output from `node --version`.

```
{ npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.11.1',
  openssl: '1.0.2k',
  uv: '1.11.0',
  v8: '5.1.281.103',
  zlib: '1.2.11' }
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
storjshare-daemon doesn't restart the node when some warn is appearing
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Sometimes farmer node restarting without visible reasons. In the log of the appropriated node we can find this error:
```
C:\Users\USER\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\storj-lib\lib\network\protocol.js:306
        this._log.warn('Unable to send exchange report to bridge: %s, '+
                 ^

TypeError: Cannot read property 'warn' of undefined
    at ClientRequest._network.bridgeRequest (C:\Users\USER\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\storj-lib\lib\network\protocol.js:306:18)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. run `storjshare daemon`
2. start the farmer node  `storjshare start --config y:\storj\storj.json`
3. After some days it's will be restarted with error above.

**Comment by Jurisg** [comment]
Got 4 node restarts after node was running ~2+days wiz out any restarts.
got same error log

/home/node/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/protocol.js:306
        this._log.warn('Unable to send exchange report to bridge: %s, '+
                 ^

TypeError: Cannot read property 'warn' of undefined
    at ClientRequest._network.bridgeRequest (/home/node/.nvm/versions/node/v6.11.2/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/protocol.js:306:18)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
