### ISSUE TITLE
Error: Failed to load the shard audit trees

### ISSUE THREAD

**Issue by redjk** [Storj/core#80]
### Package Versions

**This is running in Docker on a Synology DS415+.**

Replace the values below using the output from `npm list storj`.

```
$ sudo docker run --rm -ti --entrypoint /usr/bin/npm oreandawe/storj-farmer ls -g storj
/usr/lib
└─┬ storj-farmer@2.2.6
  └── storj@0.6.9
```

Replace the values below using the output from `node --version`.

```
$ sudo docker run --rm -ti --entrypoint /usr/bin/node oreandawe/storj-farmer --version
v4.3.0
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

**Up to this point, the program had been running nicely; these lines are pasted from the logs.**

```

{"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.6.10\",\"address\":\"149.210.229.88\",\"port\":4000,\"nodeID\":\"15cfe1362364c06af813d67a516097c3fb74d14b\",\"lastSeen\":1462553026776}","timestamp":"2016-05-06T16:43:46.776Z"}
{"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.6.10\",\"address\":\"api.storj.io\",\"port\":60542,\"nodeID\":\"18701b74838a6200df7475f089c88a9a6ae848b6\",\"lastSeen\":1462553026820}","timestamp":"2016-05-06T16:43:46.821Z"}
{"level":"warn","message":"rpc call cf138ba41e0b34f45b106c796e48cd40fa5f7a0e timed out","timestamp":"2016-05-06T16:43:46.865Z"}
{"level":"info","message":"sending OPEN_TUNNEL message to {\"protocol\":\"0.6.8\",\"address\":\"api.storj.io\",\"port\":58768,\"nodeID\":\"91c17a4ab06c8dc7400dd05f86d6343979a00264\",\"lastSeen\":1462553026865}","timestamp":"2016-05-06T16:43:46.865Z"}
{"level":"warn","message":"rpc call 95d403c0f00e1b277e0e55e5bd81d816f3acac8a timed out","timestamp":"2016-05-06T16:43:46.946Z"}
[Error: failed to establish tunnel, reason: No tunnelers were returned]
{"level":"warn","message":"you are not bound to a public address, trying traversal strategies...","timestamp":"2016-05-06T16:43:50.361Z"}
{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-05-06T16:43:50.372Z"}
{"type":"info","message":"sent telemetry report \"Success\"","timestamp":"2016-05-06T16:43:51.236Z"}

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

**Recently checked the logs and found this block repeating below.  My docker image is configured to restart automatically so it seems like Docker is trying to restart the container over and over and it throws the same error each time:**

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Failed to load the shard audit trees
    at /usr/lib/node_modules/storj-farmer/node_modules/storj/lib/storage/adapters/fs.js:123:25
    at /usr/lib/node_modules/storj-farmer/node_modules/storj/lib/storage/adapters/fs.js:301:14
    at FSReqWrap.oncomplete (fs.js:82:15)
{"level":"warn","message":"you are not bound to a public address, trying traversal strategies...","timestamp":"2016-05-06T16:43:55.069Z"}
{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-05-06T16:43:55.079Z"}
{"type":"info","message":"sent telemetry report \"Success\"","timestamp":"2016-05-06T16:43:55.889Z"}
events.js:141
      throw er; // Unhandled 'error' event
      ^
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

**Crash occurred spontaneously after running smoothly for > 36 hours. Installation was as follows:**

```
$ sudo docker run --rm -ti --name farmersetup -v /volume1/storj:/storj/ oreandawe/storj-farmer:latest
```
**Then I filled out the wizard, and hit Control-C to break. And then:**

```
$ sudo docker run -d --name farmer -v /volume1/storj:/storj/ --restart=always oreandawe/storj-farmer:latest --datadir /storj/data --password MyPassword
```
**Was working great for a while - I even got shards!**

**Comment by gordonwritescode** [comment]
I wonder if this is related to #81

**Comment by gordonwritescode** [comment]
See #84 - thanks for reporting
